##############################################################################################################
##############################################################################################################
########################### Quantile Peer Effect Models by Aristide Houndetoungan ############################
##############################################################################################################

# Last updated: 2025-02-28

# This script replicates the estimation of both quantile-based and linear-in-means models.
# For each dataset generated by `preparedata.R` and stored in OutDataPath, 
# it estimates both models and saves the results to OutResPath.
# Additionally, all estimation results are exported into a single Excel file (`Estimation.xlsx`) 
# located in OutResPath.

rm(list = ls()) 
library(dplyr)
library(QtNet)
library(PartialNetwork)
library(openxlsx)

OutDataPath <- "~/Dropbox/Data/AHdata/CleanData/" # Where prepared data for each outcome are saved (/ at the end is important)
OutResPath  <- "~/Dropbox/Academy/1.Papers/Quantile Peer Effects/Application/Outputs/" # Where results should be saved


# List of outcome variables
depvar  <- c("gpa", "academiceffort", "nclubs", "futureperception", "trouble", "smoke", "drink", "risky",
             "selfesteem", "physicalexercise", "fight")

# drop false isolated 
dropfis <- TRUE

# The following function takes an outcome and estimate the LIM and the quantile-based model
festim  <- function(outcome) {
  cat("Outcome: ", outcome, "\n", sep = "")
  ########################################################
  ################### Data Preparation ###################
  ########################################################
  load(file = paste0(OutDataPath, outcome, ".Rda")) # Load saved data using with the script 0-Data.R
  # Exogenous characteristics (excluding reference variables for identification)
  exovar  <- c("age", "age2", "grade", "grade2", "female", "hispanic", "racewhite", "raceblack", 
               "raceasian", "melhigh", "memhigh", "memiss", "mjprof", "mjother",  "mjmiss")
  y       <- data$y + 1 # + 1 because the CES-based model does not allow y <= 0
  X       <- as.matrix(data[,exovar])
  nmatch  <- data$nmatch # Number of unmatched friends
  match   <- data$match  # Number of matched friends
  iso     <- match == 0 # Isolated in of observed network
  trueiso <- (match == 0 & nmatch == 0) # True isolated
  drop    <-  rep(FALSE, length(y)) # Observation to be dropped
  if (dropfis) {
    drop  <- iso & !trueiso
  }
  Gnorm   <- norm.network(G) # Row-normalized network
  GX      <- peer.avg(Gnorm, X) 
  G2X     <- peer.avg(Gnorm, GX)  #G^2X: instrument in the standard LIM
  
  # I test two vectors for tau
  tau1    <- seq(0, 1, 1/3) # Four quantiles
  tau2    <- seq(0, 1, 1/4) # Five quantiles
  
  # First type of instruments
  Z1      <- qpeer.inst(formula = ~ X + GX, Glist = G, tau = seq(0, 1, 0.1), 
                        max.distance = 2, checkrank = TRUE, type = 7)$instruments 
  # Second type of instruments with tau1
  Z21     <- qpeer.inst(formula = y ~ X + GX, Glist = G, tau = tau1,
                        max.distance = 1, checkrank = TRUE, type = 7)$instruments
  # Second type of instruments with tau2
  Z22     <- qpeer.inst(formula = y ~ X + GX, Glist = G, tau = tau2,
                        max.distance = 1, checkrank = TRUE, type = 7)$instruments
  X       <- cbind(X, nmatch = nmatch, match = match) # Adding additional variables
  # Exogenous prediction of y for te CES
  Zces    <- fitted(lm(y ~ X + GX + as.factor(data$SCID)))
  Zces[Zces <= 0] <- min(Zces[Zces > 0]) # Because z cannot be <= 0 for the CES-based model
  
  ###############################################################
  ################### Reduced form estimation ###################
  ###############################################################
  # Linear model
  RLIM    <- summary(linpeer(formula = y ~ X + GX, 
                             excluded.instruments = ~ G2X, 
                             Glist = Gnorm,
                             drop = drop,
                             fixed.effects = "separate"), 
                     diagnostics = TRUE)
  
  # Quantile-based specification using tau1
  # Only Z1 as instruments
  RQ11    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ G2X + Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = drop,
                           tau = tau1,
                           type = 7), # Type 7 quantile
                     diagnostics = TRUE)
  
  # Only Z1 and Z21 as instruments
  RQ12    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ G2X + Z1 + Z21, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = drop,
                           tau = tau1,
                           type = 7), # Type 7 quantile
                     diagnostics = TRUE)
  
  
  # Quantile-based specification using tau2
  # Only Z1 as instruments
  RQ21    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ G2X + Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = drop,
                           tau = tau2,
                           type = 7), # Type 7 quantile
                     diagnostics = TRUE)
  
  # Only Z1 and Z2 as instruments
  RQ22    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ G2X + Z1 + Z22, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = drop,
                           tau = tau2,
                           type = 7), # Type 7 quantile
                     diagnostics = TRUE)
  
  # CES
  RCES    <- summary(cespeer(formula = y ~ X + GX, 
                             instrument = ~ Zces, 
                             Glist = Gnorm, 
                             fixed.effects = "separate",
                             drop = drop, 
                             radius = 5,
                             grid.rho = seq(-300, 300, 1)))
  
  #############################################################
  ################### Structural estimation ###################
  #############################################################
  # Linear model
  SLIM    <- summary(linpeer(formula = y ~ X + GX, 
                             excluded.instruments = ~ G2X, 
                             Glist = Gnorm,
                             fixed.effects = "separate",
                             drop = drop,
                             structural = TRUE), 
                     diagnostics = TRUE)
  
  # Quantile-based specification using tau1
  # Only Z1 as instruments
  SQ11    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ G2X + Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = drop,
                           tau = tau1,
                           type = 7, # Type 7 quantile
                           structural = TRUE),
                     diagnostics = TRUE)
  
  # Only Z1 and Z21 as instruments
  SQ12    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ G2X + Z1 + Z21, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = drop,
                           tau = tau1,
                           type = 7, # Type 7 quantile
                           structural = TRUE),
                     diagnostics = TRUE)
  
  
  # Quantile-based specification using tau2
  # Only Z1 as instruments
  SQ21    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ G2X + Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = drop,
                           tau = tau2,
                           type = 7, # Type 7 quantile
                           structural = TRUE),
                     diagnostics = TRUE)
  
  # Only Z1 and Z2 as instruments
  SQ22    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ G2X + Z1 + Z22, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = drop,
                           tau = tau2,
                           type = 7, # Type 7 quantile
                           structural = TRUE),
                     diagnostics = TRUE)
  
  # CES
  SCES    <- summary(cespeer(formula = y ~ X + GX, 
                             instrument = ~ Zces, 
                             Glist = Gnorm, 
                             structural = TRUE,
                             fixed.effects = "separate",
                             drop = drop, 
                             radius = 5,
                             grid.rho = seq(-300, 300, 1)))
  
  # Remove non-listed objects
  rm(list = setdiff(ls(), c("outcome", "depvar", "festim", "OutDataPath", "OutResPath", 
                            "RLIM", "RQ11", "RQ12", "RQ21", "RQ22", "RCES",
                            "SLIM", "SQ11", "SQ12", "SQ21", "SQ22", "SCES"))) 
  gc()
  
  # Save results
  save(RLIM, RQ11, RQ12, RQ21, RQ22, RCES, SLIM, SQ11, SQ12, SQ21, SQ22, SCES,
       file = paste0(OutResPath, outcome, ".Rda"))
  NULL # Returns nothing, the results are directly saved
}

# Estimation
sapply(depvar, festim) 

# create an Excel workbook
wb        <- createWorkbook()
addWorksheet(wb, "Estimation") # Add sheet

# Label of Outcome
OUTCOME <- c("GPA", "Academic Effort", "Clubs", "Future Perception", "Trouble", "Smoke", "Drink", "Risky",
             "Self-esteem", "Exercise", "Fight")
# tau
tau1    <- seq(0, 1, 1/3) # Four quantiles
tau2    <- seq(0, 1, 1/4) # Five quantiles

# This function puts results together
# Argument k is the index of the outcome in depvar
# Argument pval indicates if p-values of coefficients should be exported
fres <- function(k, pval = TRUE) {
  # Load results
  load(paste0(OutResPath, depvar[k], ".Rda"))
  
  ecol    <- c("Estimate", "Std. Error")
  if (pval) {
    ecol  <- c(ecol, "Pr(>|t|)") 
  }
  
  # Peer effects: structural models
  Se1     <- rbind(t(SQ11$coefficients[c(paste0("y_q", 1:length(tau1)), "y_q(conformity)"), ecol]),
                   t(c(SQ11$diagnostics[paste0("Weak instruments (y_q", 1:length(tau1), ")"), "p-value"], NA)),
                   t(c(SQ11$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau1)))))
  Se2     <- rbind(t(SQ12$coefficients[c(paste0("y_q", 1:length(tau1)), "y_q(conformity)"), ecol]),
                   t(c(SQ12$diagnostics[paste0("Weak instruments (y_q", 1:length(tau1), ")"), "p-value"], NA)),
                   t(c(SQ12$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau1)))))
  Se3     <- rbind(t(SQ21$coefficients[c(paste0("y_q", 1:length(tau2)), "y_q(conformity)"), ecol]),
                   t(c(SQ21$diagnostics[paste0("Weak instruments (y_q", 1:length(tau2), ")"), "p-value"], NA)),
                   t(c(SQ21$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau2)))))
  Se4     <- rbind(t(SQ22$coefficients[c(paste0("y_q", 1:length(tau2)), "y_q(conformity)"), ecol]),
                   t(c(SQ22$diagnostics[paste0("Weak instruments (y_q", 1:length(tau2), ")"), "p-value"], NA)),
                   t(c(SQ22$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau2)))))
  Se5     <- rbind(t(SLIM$coefficients[c("G(total):y", "G(conformity):y"), ecol]),
                   t(c(SLIM$diagnostics["Weak instruments", "p-value"], NA)),
                   t(c(SLIM$diagnostics["Hansen's J-test", "p-value"], NA)))
  Se6     <- rbind(t(SCES$coefficients[c("rho", "G(total):y", "G(conformity):y"), ecol]),
                   NA, NA)
  
  # Peer effects: reduced forms
  Re1     <- rbind(t(RQ11$coefficients[paste0("y_q", 1:length(tau1)), ecol]),
                   t(RQ11$diagnostics[paste0("Weak instruments (y_q", 1:length(tau1), ")"), "p-value"]),
                   t(c(RQ11$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau1) - 1))))
  Re2     <- rbind(t(RQ12$coefficients[paste0("y_q", 1:length(tau1)), ecol]),
                   t(RQ12$diagnostics[paste0("Weak instruments (y_q", 1:length(tau1), ")"), "p-value"]),
                   t(c(RQ12$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau1) - 1))))
  Re3     <- rbind(t(RQ21$coefficients[paste0("y_q", 1:length(tau2)), ecol]),
                   t(RQ21$diagnostics[paste0("Weak instruments (y_q", 1:length(tau2), ")"), "p-value"]),
                   t(c(RQ21$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau2) - 1))))
  Re4     <- rbind(t(RQ22$coefficients[paste0("y_q", 1:length(tau2)), ecol]),
                   t(RQ22$diagnostics[paste0("Weak instruments (y_q", 1:length(tau2), ")"), "p-value"]),
                   t(c(RQ22$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau2) - 1))))
  Re5     <- rbind(t(RLIM$coefficients["G:y", ecol, drop = FALSE]),
                   RLIM$diagnostics["Weak instruments", "p-value"],
                   RLIM$diagnostics["Hansen's J-test", "p-value"])
  Re6     <- rbind(t(RCES$coefficients[c("rho", "G:y"), ecol]),
                   NA, NA)
  
  # Put result together
  out    <- cbind(Id = NA, Id = NA, Se1, Id = NA, Se2, Id = NA, Se3, Id = NA, Se4, Id = NA, Se5, Id = NA, Se6, Id = NA, 
                  Re1, Id = NA, Re2, Id = NA, Re3, Id = NA, Re4, Id = NA, Re5, Re4, Id = NA, Re6)
  
  # Formatting
  tp        <- matrix(NA, 1, ncol(out))
  out       <- as.data.frame(rbind(tp, out, tp))
  out[1, 1] <- OUTCOME[k]
  if (pval) {
    out[2:6, 2] <- c("Mean", "StD", "Prob", "Weak Ins.", "Sargan")
  } else {
    out[2:5, 2] <- c("Mean", "StD", "Weak Ins.", "Sargan")
  }
  out
}

out   <- do.call(rbind, lapply(1:length(depvar), function(k) fres(k, TRUE))) # Includes all resulted to add to the sheet

# Add the the sheet
writeData(wb, sheet = "Estimation", x = out, startRow = 2)

# Formatting
addStyle(wb, sheet = "Estimation", style = createStyle(numFmt = "0.000"),
         cols = 2:ncol(out), rows = 3:(nrow(out) + 2), gridExpand = TRUE)
setColWidths(wb, sheet = "Estimation", cols = 2, widths = 20)
## Second row
tp     <- c("", "", rep(c(paste0("lbdatau", 1:length(tau1)), "lbda2", ""), 2),
            rep(c(paste0("lbdatau", 1:length(tau2)), "lbda2", ""), 2),
            c("lbda", "lbda2", ""),
            c("rho", "lbda", "lbda2", ""),
            rep(c(paste0("lbdatau", 1:length(tau1)), ""), 2),
            rep(c(paste0("lbdatau", 1:length(tau2)), ""), 2),
            c("lbda", ""),
            c("rho", "lbda"))
writeData(wb, sheet = "Estimation", x = t(tp), startCol = 1, startRow = 2, colNames = FALSE)
addStyle(wb, sheet = "Estimation", style = createStyle(halign = "center", fontSize = 12, textDecoration = "bold"), 
         rows = 2, cols = 1:ncol(out), gridExpand = TRUE)          
# Export
saveWorkbook(wb, file = paste0(OutResPath, "Estimation.xlsx"), overwrite = TRUE)
