##############################################################################################################
##############################################################################################################
########################### Quantile Peer Effect Models by Aristide Houndetoungan ############################
##############################################################################################################

# Last updated: 2025-02-28

# This script replicates the estimation of both quantile-based and linear-in-means models.
# For each dataset generated by `preparedata.R` and stored in OutDataPath, 
# it estimates both models and saves the results to OutResPath.
# Additionally, all estimation results are exported into a single Excel file (`Estimation.xlsx`) 
# located in OutResPath.

rm(list = ls()) 
library(dplyr)
library(QuantilePeer)
library(PartialNetwork)
library(openxlsx)

OutDataPath <- "~/Dropbox/Data/AHdata/CleanData/" # Where prepared data for each outcome are saved (/ at the end is important)
OutResPath  <- "~/Dropbox/Academy/1.Papers/Quantile Peer Effects/Application/Outputs/" # Where results should be saved


# List of outcome variables
depvar  <- c("gpa", "academiceffort", "nclubs", "futureperception", "trouble", "smoke", "drink", "risky",
             "selfesteem", "physicalexercise", "fight")

# The following function takes an outcome and estimate the LIM and the quantile-based model
fsim    <- function(outcome) {
  # cat("Outcome: ", outcome, "\n", sep = "")
  outcome <- "gpa"
  ########################################################
  ################### Data Preparation ###################
  ########################################################
  load(file = paste0(OutDataPath, outcome, ".Rda")) # Load saved data using with the script 0-Data.R
  # Exogenous characteristics (excluding reference variables for identification)
  exovar  <- c("age", "age2", "grade", "grade2", "female", "hispanic", "racewhite", "raceblack", 
               "raceasian", "melhigh", "memhigh", "memiss", "mjprof", "mjother",  "mjmiss")
  y       <- data$y + 1 # + 1 because the CES-based model does not allow y <= 0
  X       <- as.matrix(data[,exovar])
  nmatch  <- data$nmatch # Number of unmatched friends
  match   <- data$match  # Number of matched friends
  iso     <- match == 0 # Isolated in of observed network
  trueiso <- (match == 0 & nmatch == 0) # True isolated
  Gnorm   <- norm.network(G) # Row-normalized network
  GX      <- peer.avg(Gnorm, X) 
  X       <- cbind(X, nmatch = nmatch, match = match) # Adding additional variables
  
  # I test two vectors for tau
  tau1    <- seq(0, 1, 1/3) # Four quantiles
  tau2    <- seq(0, 1, 1/4) # Five quantiles
  
  # Load results
  load(paste0(OutResPath, outcome, ".Rda"))
  
  qpeer.sim(formula = y ~ X + GX, 
            Glist = Gnorm,
            tau = tau1,
            lambda = 
            type = 7)
  
  
  
  NULL # Returns nothing, the results are directly saved
}
