##############################################################################################################
##############################################################################################################
########################### Quantile Peer Effect Models by Aristide Houndetoungan ############################
##############################################################################################################

# Last updated: 2025-02-28

# This script replicates the estimation of both quantile-based and linear-in-means models.
# For each dataset generated by `preparedata.R` and stored in OutDataPath, 
# it estimates both models and saves the results to OutResPath.
# Additionally, all estimation results are exported into a single Excel file (`Estimation.xlsx`) 
# located in OutResPath.

rm(list = ls()) 
library(dplyr)
library(QuantilePeer)
library(PartialNetwork)
library(openxlsx)

OutDataPath <- "~/Dropbox/Data/AHdata/CleanData/" # Where prepared data for each outcome are saved (/ at the end is important)
OutResPath  <- "~/Dropbox/Academy/1.Papers/Quantile Peer Effects/Application/Outputs/" # Where results should be saved


# List of outcome variables
depvar  <- c("gpa", "academiceffort", "nclubs", "futureperception", "trouble", "smoke", "drink", "risky",
             "selfesteem", "physicalexercise", "fight")

# The following function takes an outcome and compute the impact of an increase in the intercept.
fsim    <- function(outcome) {
  # cat("Outcome: ", outcome, "\n", sep = "")
  outcome <- "gpa"
  cat("Outcome: ", outcome, "\n", sep = "")
  ########################################################
  ################### Data Preparation ###################
  ########################################################
  load(file = paste0(OutDataPath, outcome, ".Rda")) # Load saved data using with the script 0-Data.R
  # Exogenous characteristics (excluding reference variables for identification)
  exovar  <- c("age", "age2", "grade", "grade2", "female", "hispanic", "racewhite", "raceblack", 
               "raceasian", "melhigh", "memhigh", "memiss", "mjprof", "mjother",  "mjmiss")
  y       <- data$y + 1 # + 1 because the CES-based model does not allow y <= 0
  X       <- as.matrix(data[,exovar])
  nmatch  <- data$nmatch # Number of unmatched friends
  match   <- data$match  # Number of matched friends
  iso     <- match == 0 # Isolated in of observed network
  trueiso <- (match == 0 & nmatch == 0) # True isolated
  Gnorm   <- norm.network(G) # Row-normalized network
  GX      <- peer.avg(Gnorm, X) 
  X       <- cbind(X, nmatch = nmatch, match = match) # Adding additional variables
  
  # I test two vectors for tau
  tau1    <- seq(0, 1, 1/3) # Four quantiles
  tau2    <- seq(0, 1, 1/4) # Five quantiles
  
  # Load results
  load(paste0(OutResPath, outcome, ".Rda"))
  
  # Intercepts 1 and 2
  I1      <- rep(0, nrow(X))
  I2      <- I1 + 1
  
  #############################################################
  ######################## Simulations ########################
  #############################################################
  
  #### Linear model
  LIMsim  <- linpeer.sim(formula = ~ -1 + I2 + X + GX, 
                         Glist = Gnorm,
                         lambda = SLIM$gmm$Estimate[c("G(conformity):y", "G(total):y")],
                         beta = c(1, SLIM$gmm$Estimate[c(paste0("X", colnames(X)),
                                                         paste0("GX", colnames(GX)))]),
                         structural = TRUE,
                         epsilon = 0)$y - 
    linpeer.sim(formula = ~ -1 + I1 + X + GX, 
                Glist = Gnorm,
                lambda = SLIM$gmm$Estimate[c("G(conformity):y", "G(total):y")],
                beta = c(1, SLIM$gmm$Estimate[c(paste0("X", colnames(X)),
                                                paste0("GX", colnames(GX)))]),
                structural = TRUE,
                epsilon = 0)$y
  
  #### Quantile model
  # because this model is not linear in y, it is important to estimate the residual
  # tau1
  Xmat     <- cbind(X, GX)
  # multiply isolated individual X by 1 - lambda2
  Xmat[match > 0,] <- Xmat[match > 0,]*(1 - SQ11$gmm$Estimate["y_q(conformity)"])
  # qy
  qy       <- qpeer.instrument(y ~ 1, tau = tau1, Glist = Gnorm)$qy
  # residuals
  res      <- y - cbind(qy, Xmat) %*% SQ11$gmm$Estimate[c(paste0("y_q", 1:length(tau1)),
                                                          paste0("X", colnames(X)),
                                                          paste0("GX", colnames(GX)))]
  res[match > 0] <- res[match > 0]/(1 - SQ11$gmm$Estimate["y_q(conformity)"])
  
  Qsim1    <- qpeer.sim(formula = ~ -1 + I2 + X + GX, 
                        Glist = Gnorm,
                        tau = tau1,
                        lambda = SQ11$gmm$Estimate[c("y_q(conformity)", paste0("y_q", 1:length(tau1)))],
                        beta = c(1, SQ11$gmm$Estimate[c(paste0("X", colnames(X)),
                                                        paste0("GX", colnames(GX)))]),
                        structural = TRUE,
                        epsilon = res)$y - y # because y is the outcome before the increase in the intercept
  
  # tau2
  Xmat     <- cbind(X, GX)
  # multiply isolated individual X by 1 - lambda2
  Xmat[match > 0,] <- Xmat[match > 0,]*(1 - SQ21$gmm$Estimate["y_q(conformity)"])
  # qy
  qy       <- qpeer.instrument(y ~ 1, tau = tau2, Glist = Gnorm)$qy
  # residuals
  res      <- y - cbind(qy, Xmat) %*% SQ21$gmm$Estimate[c(paste0("y_q", 1:length(tau2)),
                                                          paste0("X", colnames(X)),
                                                          paste0("GX", colnames(GX)))]
  res[match > 0] <- res[match > 0]/(1 - SQ21$gmm$Estimate["y_q(conformity)"])
  
  Qsim2    <- qpeer.sim(formula = ~ -1 + I2 + X + GX, 
                        Glist = Gnorm,
                        tau = tau2,
                        lambda = SQ21$gmm$Estimate[c("y_q(conformity)", paste0("y_q", 1:length(tau2)))],
                        beta = c(1, SQ21$gmm$Estimate[c(paste0("X", colnames(X)),
                                                        paste0("GX", colnames(GX)))]),
                        structural = TRUE,
                        epsilon = res)$y - y # because y is the outcome before the increase in the intercept
  
  #### CES model
  # because this model is not linear in y, it is important to estimate the residual
  Xmat     <- cbind(X, GX)
  # multiply isolated individual X by 1 - lambda2
  Xmat[match > 0,] <- Xmat[match > 0,]*(1 - SCES$gmm$Estimate["G(conformity):y"])
  # social norm
  Gy       <- cespeer.data(y, Glist = Gnorm, rho = SCES$gmm$Estimate["rho"])[,"ces(y, rho)"]
  # residuals
  res      <- y - cbind(Gy, Xmat) %*% SCES$gmm$Estimate[c("G(total):y",
                                                          paste0("X", colnames(X)),
                                                          paste0("GX", colnames(GX)))]
  res[match > 0] <- res[match > 0]/(1 - SCES$gmm$Estimate["y_q(conformity)"])
  
  CESsim   <- cespeer.sim(formula = ~ -1 + I2 + X + GX, 
                          Glist = Gnorm,
                          rho = SCES$gmm$Estimate["rho"],
                          lambda = SCES$gmm$Estimate[c("G(conformity):y", "G(total):y")],
                          beta = c(1, SCES$gmm$Estimate[c(paste0("X", colnames(X)),
                                                          paste0("GX", colnames(GX)))]),
                          structural = TRUE,
                          epsilon = res)$y - y # because y is the outcome before the increase in the intercept
  saveRDS(data.frame(LIM = LIMsim, Q1 = Qsim1, Q2 = Qsim2, CES = CESsim),
          file = paste0(OutResPath, outcome, ".RDS"))
}

# Estimation
sapply(depvar, fsim) 
