##############################################################################################################
##############################################################################################################
########################### Quantile Peer Effect Models by Aristide Houndetoungan ############################
##############################################################################################################

# Last updated: 2025-04-03

# This script replicates the estimation of both quantile-based, linear-in-means, and CES models (tables 6.1 and 6.2).
# For each dataset generated by `preparedata.R` and stored in OutDataPath, 
# it estimates both models and saves the results to OutResPath.
# Additionally, all estimation results are exported into a single Excel file (`Estimation.xlsx`) 
# located in OutResPath.

rm(list = ls()) 
library(dplyr)
library(QuantilePeer)
library(PartialNetwork)
library(openxlsx)

OutDataPath <- "~/Dropbox/Data/AHdata/CleanData/" # Where prepared data for each outcome are saved (/ at the end is important)
OutResPath  <- "~/Dropbox/Academy/1.Papers/Quantile Peer Effects/Application/Outputs/" # Where results should be saved


# List of outcome variables
depvar  <- c("gpa", "academiceffort", "nclubs", "futureperception", "trouble", "smoke", "drink", "risky",
             "selfesteem", "physicalexercise", "fight")

# drop false isolated 
dropfis <- TRUE

# The following function takes an outcome and estimate the LIM, quantile-based, and the CES models.
festim  <- function(outcome) {
  cat("Outcome: ", outcome, "\n", sep = "")
  ########################################################
  ################### Data Preparation ###################
  ########################################################
  load(file = paste0(OutDataPath, outcome, ".Rda")) # Load saved data using with the script 0-Data.R
  # Exogenous characteristics (excluding reference variables for identification)
  exovar  <- c("age", "age2", "grade", "grade2", "female", "hispanic", "racewhite", "raceblack", 
               "raceasian", "melhigh", "memhigh", "memiss", "mjprof", "mjother",  "mjmiss")
  y       <- data$y + 1 # + 1 because the CES-based model does not allow y <= 0
  X       <- as.matrix(data[,exovar])
  nmatch  <- data$nmatch # Number of unmatched friends
  match   <- data$match  # Number of matched friends
  iso     <- match == 0 # Isolated in of observed network
  trueiso <- (match == 0 & nmatch == 0) # True isolated
  drop    <-  rep(FALSE, length(y)) # Observation to be dropped
  if (dropfis) {
    drop  <- iso & !trueiso
  }
  Gnorm   <- norm.network(G) # Row-normalized network
  GX      <- peer.avg(Gnorm, X) 
  G2X     <- peer.avg(Gnorm, GX)  #G^2X: instrument in the standard LIM
  
  # I test three vectors for tau
  tau3    <- seq(0, 1, 1/2) # Three quantiles
  tau4    <- seq(0, 1, 1/3) # Four quantiles
  tau5    <- seq(0, 1, 1/4) # Five quantiles
  
  # First type of instruments
  Z1      <- qpeer.inst(formula = ~ X + GX, Glist = G, tau = seq(0, 1, 0.1), 
                        max.distance = 2, checkrank = TRUE, type = 7)$instruments 
  # Second type of instruments with tau3
  Z23     <- qpeer.inst(formula = y ~ X + GX, Glist = G, tau = tau3,
                        max.distance = 2, checkrank = TRUE, type = 7)$instruments
  # Second type of instruments with tau4
  Z24     <- qpeer.inst(formula = y ~ X + GX, Glist = G, tau = tau4,
                        max.distance = 2, checkrank = TRUE, type = 7)$instruments
  # Second type of instruments with tau5
  Z25     <- qpeer.inst(formula = y ~ X + GX, Glist = G, tau = tau5,
                        max.distance = 2, checkrank = TRUE, type = 7)$instruments
  X       <- cbind(X, nmatch = nmatch, match = match) # Adding additional variables
  # Exogenous prediction of y for te CES
  Zces    <- fitted(lm(y ~ X + GX + as.factor(data$SCID)))
  Zces[Zces <= 0] <- min(Zces[Zces > 0]) # Because z cannot be <= 0 for the CES-based model
  
  #############################################################
  ################### Structural estimation ###################
  #############################################################
  # Linear model
  SLIM    <- summary(linpeer(formula = y ~ X + GX, 
                             excluded.instruments = ~ G2X, 
                             Glist = Gnorm,
                             fixed.effects = "separate",
                             drop = drop,
                             structural = TRUE), 
                     diagnostics = TRUE)
  
  # Only Z1 as instruments
  # tau3
  MSQ13   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau3,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ13    <- summary(MSQ13, diagnostics = TRUE)
  
  # tau4
  MSQ14   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau4,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ14    <- summary(MSQ14, diagnostics = TRUE)
  
  # tau5
  MSQ15   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau5,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ15    <- summary(MSQ15, diagnostics = TRUE)
  
  # Encompassing tests
  # The first test checks if the model with 3 quantiles replicates the features of the model with 4 quantiles.
  # The second test checks if the model with 4 quantiles replicates the features of the model with 5 quantiles.
  TEcomp  <- c("Test.ntau=3" = qpeer.test(MSQ13, MSQ14, which = "encompassing")$pvalue,
               "Test.ntau=4" = qpeer.test(MSQ14, MSQ15, which = "encompassing")$pvalue)
  
  # Testing Monotonicity
  TM13    <- c(U = qpeer.test(MSQ13, which = "uniform")$pvalue, 
               I = qpeer.test(MSQ13, which = "increasing")$pvalue, 
               D = qpeer.test(MSQ13, which = "decreasing")$pvalue)
  
  TM14    <- c(U = qpeer.test(MSQ14, which = "uniform")$pvalue, 
               I = qpeer.test(MSQ14, which = "increasing")$pvalue, 
               D = qpeer.test(MSQ14, which = "decreasing")$pvalue)
  
  TM15    <- c(U = qpeer.test(MSQ15, which = "uniform")$pvalue, 
               I = qpeer.test(MSQ15, which = "increasing")$pvalue, 
               D = qpeer.test(MSQ15, which = "decreasing")$pvalue)
  
  # Adding supplementary instruments (type 2 instruments)
  # tau3
  MSQ23   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1 + Z23, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau3,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ23    <- summary(MSQ23, diagnostics = TRUE)
  
  # tau4
  MSQ24   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1 + Z24, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau4,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ24    <- summary(MSQ24, diagnostics = TRUE)
  
  # tau5
  MSQ25   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1 + Z25, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau5,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ25    <- summary(MSQ25, diagnostics = TRUE)
  
  # Testing exogeneity of type 2 instruments
  TWSQ23  <- qpeer.test(MSQ13, MSQ23, which = "wald")$pvalue
  TWSQ24  <- qpeer.test(MSQ14, MSQ24, which = "wald")$pvalue
  TWSQ25  <- qpeer.test(MSQ15, MSQ25, which = "wald")$pvalue
  
  # CES
  SCES    <- summary(cespeer(formula = y ~ X + GX, 
                             instrument = ~ Zces, 
                             Glist = Gnorm, 
                             structural = TRUE,
                             fixed.effects = "separate",
                             drop = drop, 
                             radius = 5,
                             grid.rho = seq(-100, 100, 1)))
  
  # Only isolated
  # LIM
  nIRLIM  <- summary(linpeer(formula = y ~ X + GX, 
                             excluded.instruments = ~ G2X, 
                             Glist = Gnorm,
                             fixed.effects = "separate",
                             drop = ifelse(match > 0, 0, 1), # only isolated students
                             structural = FALSE), 
                     diagnostics = TRUE)
  
  # Quantile
  # tau3
  nIRQ13  <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = ifelse(match > 0, 0, 1), # only isolated students
                           tau = tau3,
                           type = 7, # Type 7 quantile
                           structural = FALSE), diagnostics = TRUE)
  
  # tau4
  nIRQ14  <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = ifelse(match > 0, 0, 1), # only isolated students
                           tau = tau4,
                           type = 7, # Type 7 quantile
                           structural = FALSE), diagnostics = TRUE)
  
  # tau5
  nIRQ15  <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = ifelse(match > 0, 0, 1), # only isolated students
                           tau = tau5,
                           type = 7, # Type 7 quantile
                           structural = FALSE), diagnostics = TRUE)
  
  # CES
  nIRCES  <- summary(cespeer(formula = y ~ X + GX, 
                             instrument = ~ Zces, 
                             Glist = Gnorm, 
                             structural = FALSE,
                             fixed.effects = "separate",
                             drop = ifelse(match > 0, 0, 1), # only isolated students
                             radius = 5,
                             grid.rho = seq(-100, 100, 1)))
  
  # Remove non-listed objects
  rm(list = setdiff(ls(), c("outcome", "depvar", "festim", "OutDataPath", "OutResPath", "dropfis",
                            "SLIM", "SQ13", "SQ14", "SQ15", "TEcomp", "TM13", "TM14", "TM15",  
                            "SQ23", "SQ24", "SQ25", "TWSQ23", "TWSQ24", "TWSQ25", "SCES",
                            "nIRLIM", "nIRQ13", "nIRQ14", "nIRQ15", "nIRCES"))) 
  gc()
  
  # Save results
  save(SLIM, SQ13, SQ14, SQ15, TEcomp, TM13, TM14, TM15,  
       SQ23, SQ24, SQ25, TWSQ23, TWSQ24, TWSQ25, SCES,
       nIRLIM, nIRQ13, nIRQ14, nIRQ15, nIRCES,
       file = paste0(OutResPath, outcome, ".Rda"))
  NULL # Returns nothing, the results are directly saved
}

# Estimation
set.seed(2025)
sapply(depvar, festim) 

# create an Excel workbook
wb        <- createWorkbook()

# Label of Outcome
OUTCOME <- c("Academic achievements (GPA)", "Academic effort", "Extracurricular activities", "Future perception", 
             "Trouble at school", "Smoking", "Drinking", "Risky behaviors", "Self-esteem", "Physical exercise", "Fighting")
# tau
tau3    <- seq(0, 1, 1/2) # Three quantiles
tau4    <- seq(0, 1, 1/3) # Four quantiles
tau5    <- seq(0, 1, 1/4) # Five quantiles

# This function puts results together
# Argument k is the index of the outcome in depvar
# Argument pval indicates if p-values of coefficients should be exported
fres <- function(k, pval = TRUE) {
  # Load results
  load(paste0(OutResPath, depvar[k], ".Rda"))
  
  ecol    <- c("Estimate", "Std. Error")
  if (pval) {
    ecol  <- c(ecol, "Pr(>|t|)") 
  }
  
  # Quantile model
  OUT   <- list()
  for (x in 3:5) {
    # Structural model
    # Z1
    SQ1    <- get(paste0("SQ1", x))
    SQ1    <- rbind(t(SQ1$coefficients[c(paste0("y_q", 1:x), "y_q(spillover)", "y_q(conformity)"), ecol]),
                    t(c(SQ1$diagnostics[paste0("Weak instruments (y_q", 1:x, ")"), "p-value"], NA, NA)),
                    t(c(SQ1$diagnostics["Hansen's J-test", "p-value"], rep(NA, 1 + x))),
                    matrix(NA, 1, 2 + x))
    # Z1 and Z2
    SQ2    <- get(paste0("SQ2", x))
    SQ2    <- rbind(t(SQ2$coefficients[c(paste0("y_q", 1:x), "y_q(spillover)", "y_q(conformity)"), ecol]),
                    t(c(SQ2$diagnostics[paste0("Weak instruments (y_q", 1:x, ")"), "p-value"], NA, NA)),
                    t(c(SQ2$diagnostics["Hansen's J-test", "p-value"], rep(NA, 1 + x))),
                    t(c(get(paste0("TWSQ2", x)), rep(NA, 1 + x))))
    # Monotonocity
    Tmo    <- rbind(t(get(paste0("TM1", x))),
                    matrix(NA, 4 + pval, 3))
    
    # Encompassing test
    Tec    <- rbind(t(TEcomp),
                    matrix(NA, 4 + pval, 2))
    
    # Reduced form
    RQ1    <- get(paste0("nIRQ1", x))
    RQ1    <- rbind(t(RQ1$coefficients[paste0("y_q", 1:x), ecol]),
                    t(RQ1$diagnostics[paste0("Weak instruments (y_q", 1:x, ")"), "p-value"]),
                    t(c(RQ1$diagnostics["Hansen's J-test", "p-value"], rep(NA, x - 1))),
                    matrix(NA, 1, x))
    # Put result together
    out           <- cbind(Id = NA, Id = NA, SQ1, Id = NA, SQ2, Id = NA, Tmo, Id = NA, Tec, Id = NA, RQ1)
    tp            <- matrix(NA, 1, ncol(out))
    out           <- as.data.frame(rbind(tp, out, tp))
    out[1, 1]     <- OUTCOME[k]
    if (pval) {
      out[2:7, 2] <- c("Mean", "StD", "Prob", "Weak Ins.", "Sargan", "Exo Z2 Sargan")
    } else {
      out[2:6, 2] <- c("Mean", "StD", "Weak Ins.", "Sargan", "Exo Z2 Sargan")
    }
    OUT[[x - 2]]  <- out
  }
   
  # LIM
  # Structural model
  SLM       <- rbind(t(SLIM$coefficients[c("G(spillover):y", "G(conformity):y"), ecol]),
                   t(c(SLIM$diagnostics["Weak instruments", "p-value"], NA)),
                   t(c(SLIM$diagnostics["Hansen's J-test", "p-value"], NA)),
                   matrix(NA, 1, 2))
  
  # Reduced form
  RLM       <- rbind(t(nIRLIM$coefficients["G:y", ecol, drop = FALSE]),
                   nIRLIM$diagnostics["Weak instruments", "p-value"],
                   nIRLIM$diagnostics["Hansen's J-test", "p-value"],
                   matrix(NA, 1, 1))
  
  out           <- cbind(Id = NA, Id = NA, SLM, Id = NA, RLM)
  tp            <- matrix(NA, 1, ncol(out))
  out           <- as.data.frame(rbind(tp, out, tp))
  out[1, 1]     <- OUTCOME[k]
  if (pval) {
    out[2:7, 2] <- c("Mean", "StD", "Prob", "Weak Ins.", "Sargan", "Exo Z2 Sargan")
  } else {
    out[2:6, 2] <- c("Mean", "StD", "Weak Ins.", "Sargan", "Exo Z2 Sargan")
  }
  OUT[[4]]      <- out
  
  # CES
  # Structural model
  SCE       <- rbind(t(SCES$coefficients[c("rho", "G(spillover):y", "G(conformity):y"), ecol]),
                   matrix(NA, 3, 3))
  
  # Reduced form
  RCE       <- rbind(t(nIRCES$coefficients[c("rho", "G:y"), ecol]),
                     matrix(NA, 3, 2))
  
  out           <- cbind(Id = NA, Id = NA, SCE, Id = NA, RCE)
  tp            <- matrix(NA, 1, ncol(out))
  out           <- as.data.frame(rbind(tp, out, tp))
  out[1, 1]     <- OUTCOME[k]
  if (pval) {
    out[2:7, 2] <- c("Mean", "StD", "Prob", "Weak Ins.", "Sargan", "Exo Z2 Sargan")
  } else {
    out[2:6, 2] <- c("Mean", "StD", "Weak Ins.", "Sargan", "Exo Z2 Sargan")
  }
  OUT[[5]]      <- out
  OUT
}

# Includes all resulted to add to the sheets
out    <- lapply(1:length(depvar), function(k) fres(k, TRUE))
out    <- lapply(1:5, function(x) {
  do.call(rbind, lapply(1:length(depvar), function(k) out[[k]][[x]]))
})

# Sheet names
shnam  <- c("3 quantiles", "4 quantiles", "5 quantiles", "LIM", "CES")

# Cells of the second rows
Srow   <- c(lapply(3:5, function (x) {
  c("", "", rep(c(paste0("lbdatau", 1:x), "lbda1", "lbda2", ""), 2),
    c("Uniform", "Increasing", "Decreasing", ""),
    c("ET dt = 3", "ET dt = 4", ""),
    c(paste0("lbdatau", 1:x), ""))
}), list(c("", "", "lbda1", "lbda2", "", "lbda", ""), 
c("", "", "rho", "lbda1", "lbda2", "", "rho", "lbda", "")))

for (x in 1:5) {
  # Adding sheet
  addWorksheet(wb, shnam[x])
  
  # Adding estimates
  writeData(wb, sheet = shnam[x], x = out[[x]], startRow = 2)
  
  # Formatting
  addStyle(wb, sheet = shnam[x], style = createStyle(numFmt = "0.000"),
           cols = 2:ncol(out[[x]]), rows = 3:(nrow(out[[x]]) + 2), gridExpand = TRUE)
  setColWidths(wb, sheet = shnam[x], cols = 2, widths = 20)
  
  ## Second row
  writeData(wb, sheet = shnam[x], x = t(Srow[[x]]), startCol = 1, startRow = 2, colNames = FALSE)
  addStyle(wb, sheet = shnam[x], style = createStyle(halign = "center", fontSize = 12, textDecoration = "bold"), 
           rows = 2, cols = 1:ncol(out[[x]]), gridExpand = TRUE)          
}

# Export
saveWorkbook(wb, file = paste0(OutResPath, "Estimation.xlsx"), overwrite = TRUE)
