##############################################################################################################
##############################################################################################################
########################### Quantile Peer Effect Models by Aristide Houndetoungan ############################
##############################################################################################################

# Last updated: 2025-04-03

# This script replicates the estimation of both quantile-based, linear-in-means, and CES models (tables 6.1 and 6.2).
# For each dataset generated by `preparedata.R` and stored in OutDataPath, 
# it estimates both models and saves the results to OutResPath.
# Additionally, all estimation results are exported into a single Excel file (`Estimation.xlsx`) 
# located in OutResPath.

rm(list = ls()) 
library(dplyr)
library(QuantilePeer)
library(PartialNetwork)
library(openxlsx)

OutDataPath <- "~/Dropbox/Data/AHdata/CleanData/" # Where prepared data for each outcome are saved (/ at the end is important)
OutResPath  <- "~/Dropbox/Academy/1.Papers/Quantile Peer Effects/Application/Outputs/" # Where results should be saved


# List of outcome variables
depvar  <- c("gpa", "academiceffort", "nclubs", "futureperception", "trouble", "smoke", "drink", "risky",
             "selfesteem", "physicalexercise", "fight")

# drop false isolated 
dropfis <- TRUE

# The following function takes an outcome and estimate the LIM, quantile-based, and the CES models.
festim  <- function(outcome) {
  cat("Outcome: ", outcome, "\n", sep = "")
  ########################################################
  ################### Data Preparation ###################
  ########################################################
  load(file = paste0(OutDataPath, outcome, ".Rda")) # Load saved data using with the script 0-Data.R
  # Exogenous characteristics (excluding reference variables for identification)
  exovar  <- c("age", "age2", "grade", "grade2", "female", "hispanic", "racewhite", "raceblack", 
               "raceasian", "melhigh", "memhigh", "memiss", "mjprof", "mjother",  "mjmiss")
  y       <- data$y + 1 # + 1 because the CES-based model does not allow y <= 0
  X       <- as.matrix(data[,exovar])
  nmatch  <- data$nmatch # Number of unmatched friends
  match   <- data$match  # Number of matched friends
  iso     <- match == 0 # Isolated in of observed network
  trueiso <- (match == 0 & nmatch == 0) # True isolated
  drop    <-  rep(FALSE, length(y)) # Observation to be dropped
  if (dropfis) {
    drop  <- iso & !trueiso
  }
  Gnorm   <- norm.network(G) # Row-normalized network
  GX      <- peer.avg(Gnorm, X) 
  G2X     <- peer.avg(Gnorm, GX)  #G^2X: instrument in the standard LIM
  
  # I test two vectors for tau
  tau1    <- seq(0, 1, 1/3) # Four quantiles
  tau2    <- seq(0, 1, 1/4) # Five quantiles
  
  # First type of instruments
  Z1      <- qpeer.inst(formula = ~ X + GX, Glist = G, tau = seq(0, 1, 0.1), 
                        max.distance = 2, checkrank = TRUE, type = 7)$instruments 
  # Second type of instruments with tau1
  Z21     <- qpeer.inst(formula = y ~ X + GX, Glist = G, tau = tau1,
                        max.distance = 1, checkrank = TRUE, type = 7)$instruments
  # Second type of instruments with tau2
  Z22     <- qpeer.inst(formula = y ~ X + GX, Glist = G, tau = tau1,
                        max.distance = 1, checkrank = TRUE, type = 7)$instruments
  X       <- cbind(X, nmatch = nmatch, match = match) # Adding additional variables
  # Exogenous prediction of y for te CES
  Zces    <- fitted(lm(y ~ X + GX + as.factor(data$SCID)))
  Zces[Zces <= 0] <- min(Zces[Zces > 0]) # Because z cannot be <= 0 for the CES-based model
  
  #############################################################
  ################### Structural estimation ###################
  #############################################################
  # Linear model
  SLIM    <- summary(linpeer(formula = y ~ X + GX, 
                             excluded.instruments = ~ G2X, 
                             Glist = Gnorm,
                             fixed.effects = "separate",
                             drop = drop,
                             structural = TRUE), 
                     diagnostics = TRUE)
  
  # Quantile-based specification using tau1
  # Only Z1 as instruments
  MSQ11   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau1,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ11    <- summary(MSQ11, diagnostics = TRUE)
  
  # Only Z21 as instruments
  MSQ12   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z21, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau1,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ12    <- summary(MSQ12, diagnostics = TRUE)
  
  # Only Z1 and Z21 as instruments
  MSQ13   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1 + Z21, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau1,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ13    <- summary(MSQ13, diagnostics = TRUE)
  
  # Testing exogeneity of Z21
  TWSQ12  <- qpeer.test(MSQ11, MSQ12, which = "wald-exogeneity")
  TJSQ13  <- qpeer.test(MSQ11, MSQ13, which = "sargan-exogeneity") # Since Z2 nests Z1 here
  TWSQ13  <- qpeer.test(MSQ11, MSQ13, which = "wald-exogeneity")
  
  # Testing Monotonicity
  TM1     <- c(U = qpeer.test(MSQ11, which = "uniform")$pvalue, 
               I = qpeer.test(MSQ11, which = "increasing")$pvalue, 
               D = qpeer.test(MSQ11, which = "decreasing")$pvalue)
  
  # Quantile-based specification using tau2
  # Only Z1 as instruments
  MSQ21   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z1, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau2,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ21    <- summary(MSQ21, diagnostics = TRUE)
  
  # Only Z22 as instruments
  MSQ22   <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ Z22, 
                   Glist = Gnorm,
                   fixed.effects = "separate",
                   drop = drop,
                   tau = tau2,
                   type = 7, # Type 7 quantile
                   structural = TRUE)
  SQ22    <- summary(MSQ22, diagnostics = TRUE)
  
  # Only Z1 and Z22 as instruments
  MSQ23    <- qpeer(formula = y ~ X + GX, 
                    excluded.instruments = ~ Z1 + Z22, 
                    Glist = Gnorm,
                    fixed.effects = "separate",
                    drop = drop,
                    tau = tau2,
                    type = 7, # Type 7 quantile
                    structural = TRUE)
  SQ23    <- summary(MSQ23, diagnostics = TRUE)
  
  # Testing exogeneity of Z22
  TWSQ22  <- qpeer.test(MSQ21, MSQ22, which = "wald-exogeneity")
  TJSQ23  <- qpeer.test(MSQ21, MSQ23, which = "sargan-exogeneity") # Since Z2 nests Z1 here
  TWSQ23  <- qpeer.test(MSQ21, MSQ23, which = "wald-exogeneity")
  
  # Testing Monotonicity
  TM2     <- c(U = qpeer.test(MSQ21, which = "uniform")$pvalue, 
               I = qpeer.test(MSQ21, which = "increasing")$pvalue, 
               D = qpeer.test(MSQ21, which = "decreasing")$pvalue)
  
  # CES
  SCES    <- summary(cespeer(formula = y ~ X + GX, 
                             instrument = ~ Zces, 
                             Glist = Gnorm, 
                             structural = TRUE,
                             fixed.effects = "separate",
                             drop = drop, 
                             radius = 5,
                             grid.rho = seq(-100, 100, 1)))
  
  # Only isolated
  nISQ1   <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = ifelse(match > 0, 0, 1), # only isolated students
                           tau = tau1,
                           type = 7, # Type 7 quantile
                           structural = FALSE), diagnostics = TRUE)
  
  nISQ2   <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ Z1, 
                           Glist = Gnorm,
                           fixed.effects = "separate",
                           drop = ifelse(match > 0, 0, 1), # only isolated students
                           tau = tau2,
                           type = 7, # Type 7 quantile
                           structural = FALSE), diagnostics = TRUE)
  
  # Remove non-listed objects
  rm(list = setdiff(ls(), c("outcome", "depvar", "festim", "OutDataPath", "OutResPath", 
                            "SLIM", "SQ11", "SQ12", "SQ13", "TWSQ12", "TJSQ13", "TWSQ13", "TM1", 
                            "SQ21", "SQ22", "SQ23", "SCES", "TWSQ22", "TJSQ23", "TWSQ23", "TM2",
                            "nISQ1", "nISQ2"))) 
  gc()
  
  # Save results
  save(SLIM, SQ11, SQ12, SQ13, TWSQ12, TJSQ13, TWSQ13, 
       SQ21, SQ22, SQ23, SCES, TWSQ22, TJSQ23, TWSQ23,
       nISQ1, nISQ2, TM1, TM2,
       file = paste0(OutResPath, outcome, ".Rda"))
  NULL # Returns nothing, the results are directly saved
}

# Estimation
sapply(depvar, festim) 

# create an Excel workbook
wb        <- createWorkbook()
addWorksheet(wb, "Estimation") # Add sheet

# Label of Outcome
OUTCOME <- c("Academic achievements (GPA)", "Academic effort", "Extracurricular activities", "Future perception", 
             "Trouble at school", "Smoking", "Drinking", "Risky behaviors", "Self-esteem", "Physical exercise", "Fighting")
# tau
tau1    <- seq(0, 1, 1/3) # Four quantiles
tau2    <- seq(0, 1, 1/4) # Five quantiles

# This function puts results together
# Argument k is the index of the outcome in depvar
# Argument pval indicates if p-values of coefficients should be exported
fres <- function(k, pval = TRUE) {
  # Load results
  load(paste0(OutResPath, depvar[k], ".Rda"))
  
  ecol    <- c("Estimate", "Std. Error")
  if (pval) {
    ecol  <- c(ecol, "Pr(>|t|)") 
  }
  
  # Peer effects: structural models
  Se1     <- rbind(t(SQ11$coefficients[c(paste0("y_q", 1:length(tau1)), "y_q(spillover)", "y_q(conformity)"), ecol]),
                   t(c(SQ11$diagnostics[paste0("Weak instruments (y_q", 1:length(tau1), ")"), "p-value"], NA, NA)),
                   t(c(SQ11$diagnostics["Hansen's J-test", "p-value"], rep(NA, 1 + length(tau1)))),
                   t(rep(NA, 2 + length(tau1))),
                   t(rep(NA, 2 + length(tau1))))
  Se2     <- rbind(t(SQ12$coefficients[c(paste0("y_q", 1:length(tau1)), "y_q(spillover)", "y_q(conformity)"), ecol]),
                   t(c(SQ12$diagnostics[paste0("Weak instruments (y_q", 1:length(tau1), ")"), "p-value"], NA, NA)),
                   t(c(SQ12$diagnostics["Hansen's J-test", "p-value"], rep(NA, 1 + length(tau1)))),
                   t(rep(NA, 2 + length(tau1))),
                   t(c(TWSQ12$pvalue, rep(NA, 1 + length(tau1)))))
  Se3     <- rbind(t(SQ13$coefficients[c(paste0("y_q", 1:length(tau1)), "y_q(spillover)", "y_q(conformity)"), ecol]),
                   t(c(SQ13$diagnostics[paste0("Weak instruments (y_q", 1:length(tau1), ")"), "p-value"], NA, NA)),
                   t(c(SQ13$diagnostics["Hansen's J-test", "p-value"], rep(NA, 1 + length(tau1)))),
                   t(c(TJSQ13$pvalue, rep(NA, 1 + length(tau1)))),
                   t(c(TWSQ13$pvalue, rep(NA, 1 + length(tau1)))))
  
  Se4     <- rbind(t(SQ21$coefficients[c(paste0("y_q", 1:length(tau2)), "y_q(spillover)", "y_q(conformity)"), ecol]),
                   t(c(SQ21$diagnostics[paste0("Weak instruments (y_q", 1:length(tau2), ")"), "p-value"], NA, NA)),
                   t(c(SQ21$diagnostics["Hansen's J-test", "p-value"], rep(NA, 1 + length(tau2)))),
                   t(rep(NA, 2 + length(tau2))),
                   t(rep(NA, 2 + length(tau2))))
  Se5     <- rbind(t(SQ22$coefficients[c(paste0("y_q", 1:length(tau2)), "y_q(spillover)", "y_q(conformity)"), ecol]),
                   t(c(SQ22$diagnostics[paste0("Weak instruments (y_q", 1:length(tau2), ")"), "p-value"], NA, NA)),
                   t(c(SQ22$diagnostics["Hansen's J-test", "p-value"], rep(NA, 1 + length(tau2)))),
                   t(rep(NA, 2 + length(tau2))),
                   t(c(TWSQ22$pvalue, rep(NA, 1 + length(tau2)))))
  Se6     <- rbind(t(SQ23$coefficients[c(paste0("y_q", 1:length(tau2)), "y_q(spillover)", "y_q(conformity)"), ecol]),
                   t(c(SQ23$diagnostics[paste0("Weak instruments (y_q", 1:length(tau2), ")"), "p-value"], NA, NA)),
                   t(c(SQ23$diagnostics["Hansen's J-test", "p-value"], rep(NA, 1 + length(tau2)))),
                   t(c(TJSQ23$pvalue, rep(NA, 1 + length(tau2)))),
                   t(c(TWSQ23$pvalue, rep(NA, 1 + length(tau2)))))
  
  Se7     <- rbind(t(SLIM$coefficients[c("G(spillover):y", "G(conformity):y"), ecol]),
                   t(c(SLIM$diagnostics["Weak instruments", "p-value"], NA)),
                   t(c(SLIM$diagnostics["Hansen's J-test", "p-value"], NA)),
                   t(rep(NA, 2)),
                   t(rep(NA, 2)))
  Se8     <- rbind(t(SCES$coefficients[c("rho", "G(spillover):y", "G(conformity):y"), ecol]),
                   t(rep(NA, 3)),
                   t(rep(NA, 3)),
                   t(rep(NA, 3)),
                   t(rep(NA, 3)))
  
  # Peer effects: reduced forms for non isolated
  Re1     <- rbind(t(nISQ1$coefficients[paste0("y_q", 1:length(tau1)), ecol]),
                   t(nISQ1$diagnostics[paste0("Weak instruments (y_q", 1:length(tau1), ")"), "p-value"]),
                   t(c(nISQ1$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau1) - 1))),
                   t(rep(NA, length(tau1))),
                   t(rep(NA, length(tau1))))
  Re2     <- rbind(t(nISQ2$coefficients[paste0("y_q", 1:length(tau2)), ecol]),
                   t(nISQ2$diagnostics[paste0("Weak instruments (y_q", 1:length(tau2), ")"), "p-value"]),
                   t(c(nISQ2$diagnostics["Hansen's J-test", "p-value"], rep(NA, length(tau2) - 1))),
                   t(rep(NA, length(tau2))),
                   t(rep(NA, length(tau2))))
  
  Tmo1    <- rbind(t(TM1),
                   matrix(NA, 5 + pval, 3))
  
  Tmo2    <- rbind(t(TM2),
                   matrix(NA, 5 + pval, 3))
  
  # Put result together
  out    <- cbind(Id = NA, Id = NA, Se1, Id = NA, Se2, Id = NA, Se3, Id = NA, Tmo1, 
                  Id = NA, Se4, Id = NA, Se5, Id = NA, Se6, Id = NA, Tmo2, 
                  Id = NA, Se7, Id = NA, Se8, 
                  Id = NA, Re1, Id = NA, Re2)
  
  # Formatting
  tp        <- matrix(NA, 1, ncol(out))
  out       <- as.data.frame(rbind(tp, out, tp))
  out[1, 1] <- OUTCOME[k]
  if (pval) {
    out[2:8, 2] <- c("Mean", "StD", "Prob", "Weak Ins.", "Sargan", "Exo Z2 Sargan", "Exo Z2 Wald")
  } else {
    out[2:7, 2] <- c("Mean", "StD", "Weak Ins.", "Sargan", "Exo Z2 Sargan", "Exo Z2 Wald")
  }
  out
}

out   <- do.call(rbind, lapply(1:length(depvar), function(k) fres(k, TRUE))) # Includes all resulted to add to the sheet

# Add the the sheet
writeData(wb, sheet = "Estimation", x = out, startRow = 2)

# Formatting
addStyle(wb, sheet = "Estimation", style = createStyle(numFmt = "0.000"),
         cols = 2:ncol(out), rows = 3:(nrow(out) + 2), gridExpand = TRUE)
setColWidths(wb, sheet = "Estimation", cols = 2, widths = 20)
## Second row
tp     <- c("", "", rep(c(paste0("lbdatau", 1:length(tau1)), "lbda1", "lbda2", ""), 3),
            c("Uniform", "Increasing", "Decreasing", ""),
            rep(c(paste0("lbdatau", 1:length(tau2)), "lbda1", "lbda2", ""), 3),
            c("Uniform", "Increasing", "Decreasing", ""),
            c("lbda1", "lbda2", ""),
            c("rho", "lbda1", "lbda2", ""),
            c(paste0("lbdatau", 1:length(tau1)), ""),
            c(paste0("lbdatau", 1:length(tau2)), ""))
writeData(wb, sheet = "Estimation", x = t(tp), startCol = 1, startRow = 2, colNames = FALSE)
addStyle(wb, sheet = "Estimation", style = createStyle(halign = "center", fontSize = 12, textDecoration = "bold"), 
         rows = 2, cols = 1:ncol(out), gridExpand = TRUE)          
# Export
saveWorkbook(wb, file = paste0(OutResPath, "Estimation.xlsx"), overwrite = TRUE)
