################################################################################
################################################################################
################ Identification of Heterogeneous Peer Effects ##################
########### Eyo I. Herstad, Aristide Houndetoungan, Myungkou Shin ##############
################################################################################
################################################################################

# Last updated: 2026-06-09

# This script replicates the estimation of both quantile-based, linear-in-means, 
# and CES models (tables 5.1, 5.2, E.1, and E.2). For each dataset generated by `AddHealth.data.R` 
# and stored in OutDataPath, it estimates the models and saves the results to OutResPath.
# All estimation results are exported into a single Excel file (`Estimation.xlsx`)
# located in OutResPath. The Excel contains has the following sheets:
#  - Table 5.1 (reproduces Table 5.1),
#  - Table 5.2 (reproduces Table 5.2),
#  - Table E.1 (reproduces Table E.1),
#  - Table E.2 (reproduces Table E.2),
#  - Full results (not included in the paper).

rm(list = ls()) 
library(dplyr)
library(QuantilePeer)
library(CDatanet)
library(openxlsx)

OutDataPath <- "PATH/TO/WHERE/PREPARED/DATA/IS/SAVED" # Where prepared data for each outcome are saved (/ at the end is important)
OutResPath  <- "PATH/TO/WHERE/RESULTS/WILL/BE/SAVED" # Where results should be saved

# List of outcome variables
depvar  <- c("gpa", "academiceffort", "nclubs", "futureperception", "trouble", "smoke", "drink", "risky",
             "selfesteem", "physicalexercise", "fight")

# drop false isolated 
dropfis <- FALSE

# The following function takes an outcome and estimate the LIM, quantile-based, 
# and the CES models.
festim  <- function(outcome, nthreads) {
  cat("Outcome: ", outcome, "\n", sep = "")
  ########################################################
  ################### Data Preparation ###################
  ########################################################
  load(file = paste0(OutDataPath, "/", outcome, ".Rda")) # Load saved data using with the script 0-Data.R
  # Exogenous characteristics (excluding reference variables for identification)
  exovar  <- c("age", "age2", "grade", "grade2", "female", "hispanic", "racewhite", "raceblack", 
               "raceasian", "melhigh", "memhigh", "memiss", "mjprof", "mjother",  "mjmiss")
  y       <- data$y + 1 # + 1 because the CES-based model does not allow y <= 0
  X       <- as.matrix(data[,exovar])
  nmatch  <- data$nmatch # Number of unmatched friends
  match   <- data$match  # Number of matched friends
  iso     <- match == 0 # Isolated in of observed network
  trueiso <- (match == 0 & nmatch == 0) # True isolated
  drop    <-  rep(FALSE, length(y)) # Observation to be dropped (we drop false isolated)
  if (dropfis) {
    drop  <- iso & !trueiso
  }
  Gnorm   <- norm.network(G) # Row-normalized network
  GX      <- peer.avg(Gnorm, X) 
  G2X     <- peer.avg(Gnorm, GX)  #G^2X: instrument in the standard LIM
  
  # I test three vectors for tau
  tau3    <- seq(0, 1, 1/2) # Three quantiles
  tau4    <- seq(0, 1, 1/3) # Four quantiles
  tau5    <- seq(0, 1, 1/4) # Five quantiles
  
  # Quantile of peer as instrument (like OLS)
  Qy3     <- qpeer.inst(formula = ~y, A = G, tau = tau3, 
                        max.distance = 1, type = 7)$instruments
  
  Qy4     <- qpeer.inst(formula = ~y, A = G, tau = tau4, 
                        max.distance = 1, type = 7)$instruments
  
  Qy5     <- qpeer.inst(formula = ~y, A = G, tau = tau5, 
                        max.distance = 1, type = 7)$instruments
  
  # Quantile of X instruments
  ZQ      <- cbind(qpeer.inst(formula = ~ X + GX, A = G, tau = seq(0, 1, 1/9), 
                              max.distance = 2, checkrank = TRUE, type = 7)$instruments)
  
  X       <- cbind(X, nmatch = nmatch, match = match) # Adding additional variables
  # Exogenous prediction of y for the CES
  Zces    <- fitted(lm(y ~ X + GX + as.factor(data$SCID)))
  Zces[Zces <= 0] <- min(Zces[Zces > 0]) # Because z cannot be <= 0 for the CES-based model
  
  #############################################################
  ######################### estimation ########################
  #############################################################
  # Linear model
  LIM     <- summary(linpeer(formula = y ~ X + GX, 
                             excluded.instruments = ~ G2X, 
                             A = Gnorm,
                             fixed.effects = "separate",
                             drop = drop,
                             HAC = "cluster"), 
                     diagnostics = TRUE)
  
  # Quantile models IV
  # tau3
  MQ3     <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ ZQ, 
                   A = Gnorm,
                   fixed.effects = "separate",
                   tau = tau3,
                   type = 7,
                   drop = drop,
                   HAC = "cboot",
                   boot = 1e4,
                   nthreads = nthreads)
  Q3      <- summary(MQ3)
  
  # tau4
  MQ4     <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ ZQ, 
                   A = Gnorm,
                   fixed.effects = "separate",
                   tau = tau4,
                   type = 7,
                   drop = drop,
                   HAC = "cboot",
                   boot = 1e4,
                   nthreads = nthreads)
  Q4      <- summary(MQ4)
  
  # Uncluttered
  Q4u     <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ ZQ, 
                           A = Gnorm,
                           fixed.effects = "separate",
                           tau = tau4,
                           type = 7,
                           drop = drop), diagnostics = TRUE)
  
  # tau5
  MQ5     <- qpeer(formula = y ~ X + GX, 
                   excluded.instruments = ~ ZQ, 
                   A = Gnorm,
                   fixed.effects = "separate",
                   tau = tau5,
                   type = 7,
                   drop = drop,
                   HAC = "cboot",
                   boot = 1e4,
                   nthreads = nthreads) 
  Q5      <- summary(MQ5)
  
  
  # Quantile models OLS
  # tau3
  OLSQ3   <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ Qy3, 
                           A = Gnorm,
                           fixed.effects = "separate",
                           tau = tau3,
                           type = 7,
                           drop = drop,
                           HAC = "cluster",
                           nthreads = nthreads))
  
  # tau4
  OLSQ4   <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ Qy4, 
                           A = Gnorm,
                           fixed.effects = "separate",
                           tau = tau4,
                           type = 7,
                           drop = drop,
                           HAC = "cluster",
                           nthreads = nthreads))
  
  # tau5
  OLSQ5   <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ Qy5, 
                           A = Gnorm,
                           fixed.effects = "separate",
                           tau = tau4,
                           type = 7,
                           drop = drop,
                           HAC = "cluster",
                           nthreads = nthreads))
  
  # Encompassing tests
  # The first test checks if the model with 3 quantiles replicates the features of the model with 4 quantiles.
  # The second test checks if the model with 4 quantiles replicates the features of the model with 5 quantiles.
  TEcomp  <- c("Test.ntau=3.4" = qpeer.test(MQ3, MQ4, which = "encompassing",
                                            boot = 1e4, nthreads = nthreads)$test["KP Wald rank", "p-value"],
               "Test.ntau=4.3" = qpeer.test(MQ4, MQ3, which = "encompassing",
                                            boot = 1e4, nthreads = nthreads)$test["KP Wald rank", "p-value"],
               "Test.ntau=4.5" = qpeer.test(MQ4, MQ5, which = "encompassing",
                                            boot = 1e4, nthreads = nthreads)$test["KP Wald rank", "p-value"])
  
  # Testing Monotonicity
  TM3     <- c(U = qpeer.test(MQ3, which = "uniform")$test["p-value"], 
               I = qpeer.test(MQ3, which = "increasing")$test["p-value"], 
               D = qpeer.test(MQ3, which = "decreasing")$test["p-value"])
  
  TM4     <- c(U = qpeer.test(MQ4, which = "uniform")$test["p-value"], 
               I = qpeer.test(MQ4, which = "increasing")$test["p-value"], 
               D = qpeer.test(MQ4, which = "decreasing")$test["p-value"])
  
  TM5     <- c(U = qpeer.test(MQ5, which = "uniform")$test["p-value"], 
               I = qpeer.test(MQ5, which = "increasing")$test["p-value"], 
               D = qpeer.test(MQ5, which = "decreasing")$test["p-value"])
  
  # CES
  CES     <- summary(cespeer(formula = y ~ X + GX, 
                             instrument = ~ Zces, 
                             A = Gnorm, 
                             fixed.effects = "separate",
                             drop = drop,
                             radius = 5,
                             grid.rho = seq(-100, 100, 1),
                             HAC = "cluster"))
  
  # Only isolated
  # LIM
  nILIM   <- summary(linpeer(formula = y ~ X + GX, 
                             excluded.instruments = ~ G2X, 
                             A = Gnorm,
                             fixed.effects = "separate",
                             HAC = "cluster",
                             drop = ifelse(match > 0, 0, 1)), # only isolated students
                     diagnostics = TRUE)
  
  # Quantile
  # tau3
  nIQ3    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ ZQ, 
                           A = Gnorm,
                           fixed.effects = "separate",
                           tau = tau3,
                           type = 7,
                           HAC = "cboot",
                           boot = 1e4,
                           nthreads = nthreads,
                           drop = ifelse(match > 0, 0, 1))) # only isolated students
  
  # tau4
  nIQ4    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ ZQ, 
                           A = Gnorm,
                           fixed.effects = "separate",
                           tau = tau4,
                           type = 7,
                           HAC = "cboot",
                           boot = 1e4,
                           nthreads = nthreads,
                           drop = ifelse(match > 0, 0, 1))) # only isolated students
  
  # tau5
  nIQ5    <- summary(qpeer(formula = y ~ X + GX, 
                           excluded.instruments = ~ ZQ, 
                           A = Gnorm,
                           fixed.effects = "separate",
                           tau = tau5,
                           type = 7,
                           HAC = "cboot",
                           boot = 1e4,
                           nthreads = nthreads,
                           drop = ifelse(match > 0, 0, 1))) # only isolated students
  
  # CES
  nICES   <- summary(cespeer(formula = y ~ X + GX, 
                             instrument = ~ Zces, 
                             A = Gnorm, 
                             fixed.effects = "separate",
                             radius = 5,
                             grid.rho = seq(-100, 100, 1),
                             HAC = "cluster",
                             drop = ifelse(match > 0, 0, 1))) # only isolated students
  
  # Remove non-listed objects
  rm(list = setdiff(ls(), c("outcome", "depvar", "festim", "OutDataPath", "OutResPath", "dropfis",
                            "LIM", "Q3", "Q4", "Q4u", "Q5", "OLSQ3", "OLSQ4", "OLSQ5", "CES", 
                            "TEcomp", "TM3", "TM4", "TM5", "nILIM", "nIQ3", "nIQ4", "nIQ5", "nICES"))) 
  gc()
  
  # Save results
  save(LIM, Q3, Q4, Q4u, Q5, OLSQ3, OLSQ4, OLSQ5, TEcomp, TM3, TM4, TM5, CES,
       nILIM, nIQ3, nIQ4, nIQ5, nICES,
       file = paste0(OutResPath, "/", outcome, ".Rda"))
  NULL # Returns nothing, the results are directly saved
}

# Estimation
set.seed(2025)
nthreads <- 50
sapply(depvar, \(outcome) festim(outcome, nthreads))

# Label of Outcome
OUTCOME <- c("Academic achievements (GPA)", "Academic effort", "Extracurricular activities", "Future perception", 
             "Trouble at school", "Smoking", "Drinking", "Risky behaviors", "Self-esteem", "Physical exercise", "Fighting")
# tau
tau3    <- seq(0, 1, 1/2) # Three quantiles
tau4    <- seq(0, 1, 1/3) # Four quantiles
tau5    <- seq(0, 1, 1/4) # Five quantiles

# This function puts results together
# Argument k is the index of the outcome in depvar
fres <- function(k) {
  # Load results
  load(paste0(OutResPath, "/", depvar[k], ".Rda"))
  
  # For Tables 5.1 and 5.2
  ecol       <- c("Estimate", "Std. Error") 
  T5.1       <- rbind(NA, data.frame(cbind(
    t(Q4$coefficients[paste0("y_q", 1:4), ecol]), V1 = NA,
    LIM$coefficients["A:y", ecol], V2 = NA,
    t(CES$coefficients[c("rho", "A:y"), ecol])))  %>% 
      mutate(across(where(is.numeric), ~ ifelse(is.na(.), NA, sprintf("%.3f", .)))) %>%  # Ensures exactly 3 decimals
      mutate(across(everything(), ~ ifelse(
        is.na(.), NA,
        ifelse(row_number() %% 2 == 0, paste0("(", trimws(.), ")"), .)
      ))))  # Parentheses without spaces 
  T5.1[1, 1] <- OUTCOME[k]
  
  T5.2       <- rbind(NA, data.frame(cbind(
    rbind(t(TEcomp[c("Test.ntau=3.4", "Test.ntau=4.5")]), NA), NA, # Encompassing, ntau = 4 against ntau = 5  
    rbind(Q4u$diagnostics[paste0("Kleibergen-Paap rk Wald"), "p-value"], NA), NA, # KP rank stat
    rbind(TM4, NA) # Monotonicity test
  )) %>%  
    mutate(across(where(is.numeric), ~ ifelse(is.na(.), NA, sprintf("%.3f", .)))) %>%  # Ensures exactly 3 decimals
    filter(row_number() != 2))
  T5.2[1, 1] <- OUTCOME[k]
  
  # Sample size TE.1
  TE.1       <- data.frame(V1 = OUTCOME[k], n = Q4$model.info$n)
  
  # Table E.2 (5 quantiles)
  TE.2       <- rbind(NA, data.frame(cbind(
    t(Q5$coefficients[paste0("y_q", 1:5), ecol]), V1 = NA,
    t(nIQ4$coefficients[paste0("y_q", 1:4), ecol])))  %>% 
      mutate(across(where(is.numeric), ~ ifelse(is.na(.), NA, sprintf("%.3f", .)))) %>%  # Ensures exactly 3 decimals
      mutate(across(everything(), ~ ifelse(
        is.na(.), NA,
        ifelse(row_number() %% 2 == 0, paste0("(", trimws(.), ")"), .)
      ))))  # Parentheses without spaces 
  TE.2[1, 1] <- OUTCOME[k]
  
  
  # Table E.3 OLS (4 quantiles)
  TE.3       <- rbind(NA, data.frame(cbind(
    t(OLSQ4$coefficients[paste0("y_q", 1:4), ecol]), V1 = NA,
    t(nIQ4$coefficients[paste0("y_q", 1:4), ecol]), V2 = NA,
    c(Q4u$diagnostics["Wu-Hausman", "p-value"], NA)))  %>% 
      mutate(across(where(is.numeric), ~ ifelse(is.na(.), NA, sprintf("%.3f", .)))) %>%  # Ensures exactly 3 decimals
      mutate(across(everything(), ~ ifelse(
        is.na(.), NA,
        ifelse(row_number() %% 2 == 0, paste0("(", trimws(.), ")"), .)
      ))))  # Parentheses without spaces 
  TE.3[1, 1] <- OUTCOME[k]
  
  # Full results (do not include OLS)
  ecol    <- c("Estimate", "Std. Error", "Pr(>|t|)") 
  # Quantile model
  Qtl     <- list()
  for (x in 3:5) {
    Q        <- get(paste0("Q", x))
    nIQ      <- get(paste0("nIQ", x))
    if (x %in% 4) { # because diagnostics are available
      Qu     <- get(paste0("Q", x, "u"))
      # Full data
      Q      <- rbind(t(Q$coefficients[paste0("y_q", 1:x), ecol]),
                      t(c(Qu$diagnostics[paste0("Kleibergen-Paap rk Wald"), "statistic"], rep(NA, x - 1))), 
                      t(c(Qu$diagnostics[paste0("Kleibergen-Paap rk Wald"), "df1"], rep(NA, x - 1))),
                      t(c(Qu$diagnostics[paste0("Kleibergen-Paap rk Wald"), "p-value"], rep(NA, x - 1))),
                      matrix(NA, 2, x))
      
      # Without isolates
      nIQ    <- rbind(t(nIQ$coefficients[paste0("y_q", 1:x), ecol]),
                      matrix(NA, 5, x))
    } else {
      # Full data
      Q      <- rbind(t(Q$coefficients[paste0("y_q", 1:x), ecol]),
                      matrix(NA, 5, x))
      
      # Without isolates
      nIQ    <- rbind(t(nIQ$coefficients[paste0("y_q", 1:x), ecol]),
                      matrix(NA, 5, x))
    }
    
    
    # Monotonocity
    Tmo    <- rbind(t(get(paste0("TM", x))),
                    matrix(NA, 7, 3))
    
    # Put result together
    Qtlx    <- NULL
    
    if (x == 4) {
      # Encompassing test
      Tec  <- rbind(t(TEcomp),
                    matrix(NA, 7, 3))
      Qtlx <- cbind(Q, Id = NA, Tmo, Id = NA, Tec, Id = NA, nIQ, Id = NA)
    } else {
      Qtlx <- cbind(Q, Id = NA, Tmo, Id = NA, nIQ, Id = NA)
    }
    Qtl[[x - 2]]  <- Qtlx
  }
  
  # LIM
  # Full data
  LM        <- rbind(t(LIM$coefficients["A:y", ecol, drop = FALSE]),
                     matrix(NA, 5, 1))
  
  # Without isolates
  nILM      <- rbind(t(nILIM$coefficients["A:y", ecol, drop = FALSE]),
                     matrix(NA, 5, 1))
  
  # CES
  # Full data
  CES       <- rbind(t(CES$coefficients[c("rho", "A:y"), ecol]),
                     matrix(NA, 5, 2))
  
  # Without isolates
  nICES     <- rbind(t(nICES$coefficients[c("rho", "A:y"), ecol]),
                     matrix(NA, 5, 2))
  
  out           <- cbind(Id = NA, Id = NA, do.call(cbind, Qtl), LM, Id = NA, nILM, 
                         Id = NA, CES, Id = NA, nICES)
  tp            <- matrix(NA, 1, ncol(out))
  out           <- as.data.frame(rbind(tp, out, tp))
  out[1, 1]     <- OUTCOME[k]
  out[2:9, 2]  <- c("Mean", "StD", "Prob", 
                    "KP rk - Stat", "KP rk - df", "KP rk - pvalue", 
                    "Exo Z2 Sargan", "Exo Z2 Wald")
  list(T5.1 = T5.1, T5.2 = T5.2, 
       TE.1 = TE.1, TE.2 = TE.2, TE.3 = TE.3, Full = out)
}

# Includes all resulted to add to the sheets
out    <- lapply(1:length(depvar), fres)
T5.1   <- do.call(rbind, lapply(out, function(x) x$T5.1))
T5.2   <- do.call(rbind, lapply(out, function(x) x$T5.2))
TE.1   <- do.call(rbind, lapply(out, function(x) x$TE.1))
TE.2   <- do.call(rbind, lapply(out, function(x) x$TE.2))
TE.3   <- do.call(rbind, lapply(out, function(x) x$TE.3))
Full   <- do.call(rbind, lapply(1:length(out), function(k) out[[k]][["Full"]]))

# Write data
# create an Excel workbook
wb        <- createWorkbook()

# Table 5.1 
addWorksheet(wb, "Table 5.1")
writeData(wb, "Table 5.1", x = T5.1, startRow = 2)
# first row
fr    <- c(paste("ld_q", 1:4), "", "ld", "", "rho", "ld")
for (i in 1:length(fr)) {
  writeData(wb, "Table 5.1", fr[i], startRow = 2, startCol = i)
}
# Merge cells
for (i in seq(1, nrow(T5.1), 3) + 2) {
  mergeCells(wb, "Table 5.1", cols = 1:ncol(T5.1), rows = i)
}
# Formatting
addStyle(wb, "Table 5.1", style = createStyle(halign = "center"), 
         rows = 2:(nrow(T5.1) + 2), cols = 1:ncol(T5.1), gridExpand = TRUE)  

# Table 5.2
addWorksheet(wb, "Table 5.2")
writeData(wb, "Table 5.2", x = T5.2, startRow = 2)
# first row
fr    <- c("Ecom 3vs4", "Ecom 4vs5", "", "KP", "", "Uniform", "Increasing", "Decreasing")
for (i in 1:length(fr)) {
  writeData(wb, "Table 5.2", fr[i], startRow = 2, startCol = i)
}
# Merge cells
for (i in seq(1, nrow(T5.2), 2) + 2) {
  mergeCells(wb, "Table 5.2", cols = 1:ncol(T5.2), rows = i)
}
# Formatting
addStyle(wb, "Table 5.2", style = createStyle(halign = "center"), 
         rows = 2:(nrow(T5.2) + 2), cols = 1:ncol(T5.2), gridExpand = TRUE) 

# Table E.1
addWorksheet(wb, "Table E.1")
writeData(wb, "Table E.1", x = TE.1, startRow = 2)
# first row
fr    <- c("Outcome", "$n$")
for (i in 1:length(fr)) {
  writeData(wb, "Table E.1", fr[i], startRow = 2, startCol = i)
}


# Table E.2
addWorksheet(wb, "Table E.2")
writeData(wb, "Table E.2", x = TE.2, startRow = 2)
# first row
fr    <- c(paste("ld_q", 1:5), "", paste("ld_q", 1:4))
for (i in 1:length(fr)) {
  writeData(wb, "Table E.2", fr[i], startRow = 2, startCol = i)
}
# Merge cells
for (i in seq(1, nrow(TE.2), 3) + 2) {
  mergeCells(wb, "Table E.2", cols = 1:ncol(TE.2), rows = i)
}
# Formatting
addStyle(wb, "Table E.2", style = createStyle(halign = "center"), 
         rows = 2:(nrow(TE.2) + 2), cols = 1:ncol(TE.2), gridExpand = TRUE) 


# Table E.3
addWorksheet(wb, "Table E.3")
writeData(wb, "Table E.3", x = TE.3, startRow = 2)
# first row
fr    <- c(paste("ld_q", 1:4), "", paste("ld_q", 1:4), "", "Wu-Hausman")
for (i in 1:length(fr)) {
  writeData(wb, "Table E.3", fr[i], startRow = 2, startCol = i)
}
# Merge cells
for (i in seq(1, nrow(TE.3), 3) + 2) {
  mergeCells(wb, "Table E.3", cols = 1:ncol(TE.3), rows = i)
}
# Formatting
addStyle(wb, "Table E.3", style = createStyle(halign = "center"), 
         rows = 2:(nrow(TE.3) + 2), cols = 1:ncol(TE.3), gridExpand = TRUE) 

# Full results
addWorksheet(wb, "Full results")
writeData(wb, "Full results", x = Full, startRow = 2)

# Formatting
addStyle(wb, sheet = "Full results", style = createStyle(numFmt = "0.000"),
         cols = 2:ncol(Full), rows = 3:(nrow(Full) + 2), gridExpand = TRUE)
setColWidths(wb, sheet = "Full results", cols = 2, widths = 20)

## First row
fr  <- c("ntau = 3, Full data", 
         "ntau = 3, Monotonicity", 
         "ntau = 3, Without isolated",
         "ntau = 4, Full data", 
         "ntau = 4, Monotonicity", "ntau = 4, Encompassing", 
         "ntau = 4, Without isolated",
         "ntau = 5, Full data",
         "ntau = 5, Monotonicity", 
         "ntau = 5, Without isolated",
         "LIM, Full data", "LIM, Without isolated", 
         "CES, Full data", "CES, Without isolated")
ifr <- cumsum(c(3, 4, 4, 4, 5, 4, 4, 5, 6, 4, 6, 2, 2, 3))
for (i in 1:length(fr)) {
  writeData(wb, "Full results", x = fr[i], startCol = ifr[i], startRow = 1, colNames = FALSE)
}

## Second row
sr  <- c(rep("", 2), paste0("ld_q", 1:3), "",
         "Uniform", "Increasing", "Decreasing", "", paste0("ld_q", 1:3), "",
         paste0("ld_q", 1:4), "", 
         "Uniform", "Increasing", "Decreasing", "", 
         "3 against 4", "4 against 3", "4 against 5", "", paste0("ld_q", 1:4), "",
         paste0("ld_q", 1:5), "",
         "Uniform", "Increasing", "Decreasing", "", paste0("ld_q", 1:5), "",
         "ld", "", "ld", "", "rho", "ld", "", "rho", "ld")
for (i in 1:length(sr)) {
  writeData(wb, "Full results", x = sr[i], startCol = i, startRow = 2, colNames = FALSE)
}


# Export
saveWorkbook(wb, file = paste0(OutResPath, "/Estimation.xlsx"), overwrite = TRUE)

