// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fQtauy
arma::mat fQtauy(const arma::vec& y, Rcpp::List& G, const arma::vec d, const arma::mat& igroup, const arma::vec& nvec, const arma::vec& stau, const int& ngroup, const int& n, const int& ntau, const int& type);
RcppExport SEXP _QtNet_fQtauy(SEXP ySEXP, SEXP GSEXP, SEXP dSEXP, SEXP igroupSEXP, SEXP nvecSEXP, SEXP stauSEXP, SEXP ngroupSEXP, SEXP nSEXP, SEXP ntauSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type stau(stauSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type ntau(ntauSEXP);
    Rcpp::traits::input_parameter< const int& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(fQtauy(y, G, d, igroup, nvec, stau, ngroup, n, ntau, type));
    return rcpp_result_gen;
END_RCPP
}
// fQtauyWithIndex
Rcpp::List fQtauyWithIndex(const arma::vec& y, Rcpp::List& G, const arma::vec d, const arma::mat& igroup, const arma::vec& nvec, const arma::vec& stau, const int& ngroup, const int& n, const int& ntau, const int& type);
RcppExport SEXP _QtNet_fQtauyWithIndex(SEXP ySEXP, SEXP GSEXP, SEXP dSEXP, SEXP igroupSEXP, SEXP nvecSEXP, SEXP stauSEXP, SEXP ngroupSEXP, SEXP nSEXP, SEXP ntauSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type stau(stauSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type ntau(ntauSEXP);
    Rcpp::traits::input_parameter< const int& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(fQtauyWithIndex(y, G, d, igroup, nvec, stau, ngroup, n, ntau, type));
    return rcpp_result_gen;
END_RCPP
}
// fQtauyIndex
Rcpp::List fQtauyIndex(const arma::vec& y, Rcpp::List& G, const arma::vec d, const arma::mat& igroup, const arma::vec& nvec, const arma::vec& stau, const int& ngroup, const int& n, const int& ntau, const int& type);
RcppExport SEXP _QtNet_fQtauyIndex(SEXP ySEXP, SEXP GSEXP, SEXP dSEXP, SEXP igroupSEXP, SEXP nvecSEXP, SEXP stauSEXP, SEXP ngroupSEXP, SEXP nSEXP, SEXP ntauSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type stau(stauSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type ntau(ntauSEXP);
    Rcpp::traits::input_parameter< const int& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(fQtauyIndex(y, G, d, igroup, nvec, stau, ngroup, n, ntau, type));
    return rcpp_result_gen;
END_RCPP
}
// fIndexMat
arma::sp_mat fIndexMat(const arma::uvec& pi1, const arma::uvec& pi2, const arma::vec& w1, const arma::vec& w2, const int& n);
RcppExport SEXP _QtNet_fIndexMat(SEXP pi1SEXP, SEXP pi2SEXP, SEXP w1SEXP, SEXP w2SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type pi1(pi1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pi2(pi2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(fIndexMat(pi1, pi2, w1, w2, n));
    return rcpp_result_gen;
END_RCPP
}
// fProdWVI
arma::mat fProdWVI(const arma::sp_mat& W, const arma::mat& V, const int& distance);
RcppExport SEXP _QtNet_fProdWVI(SEXP WSEXP, SEXP VSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const int& >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(fProdWVI(W, V, distance));
    return rcpp_result_gen;
END_RCPP
}
// fNashE
int fNashE(arma::vec& y, Rcpp::List& G, const arma::vec d, const arma::vec& talpha, const arma::vec& lambdatau, const arma::mat& igroup, const arma::vec& nvec, const arma::vec& stau, const int& ngroup, const int& n, const int& ntau, const int& type, const double& tol, const int& maxit);
RcppExport SEXP _QtNet_fNashE(SEXP ySEXP, SEXP GSEXP, SEXP dSEXP, SEXP talphaSEXP, SEXP lambdatauSEXP, SEXP igroupSEXP, SEXP nvecSEXP, SEXP stauSEXP, SEXP ngroupSEXP, SEXP nSEXP, SEXP ntauSEXP, SEXP typeSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type talpha(talphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambdatau(lambdatauSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type stau(stauSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type ntau(ntauSEXP);
    Rcpp::traits::input_parameter< const int& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(fNashE(y, G, d, talpha, lambdatau, igroup, nvec, stau, ngroup, n, ntau, type, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// optins_red
arma::mat optins_red(const arma::vec& beta, const arma::vec& y, Rcpp::List& G, const arma::mat& X, const arma::vec d, const arma::mat& igroup, const arma::vec& nvec, const arma::vec& stau, const int& ngroup, const int& n, const int& ntau, const int& type, const int& Kx, const double& tol, const int& maxit);
RcppExport SEXP _QtNet_optins_red(SEXP betaSEXP, SEXP ySEXP, SEXP GSEXP, SEXP XSEXP, SEXP dSEXP, SEXP igroupSEXP, SEXP nvecSEXP, SEXP stauSEXP, SEXP ngroupSEXP, SEXP nSEXP, SEXP ntauSEXP, SEXP typeSEXP, SEXP KxSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type stau(stauSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type ntau(ntauSEXP);
    Rcpp::traits::input_parameter< const int& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(optins_red(beta, y, G, X, d, igroup, nvec, stau, ngroup, n, ntau, type, Kx, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// optins_struc
arma::mat optins_struc(const arma::vec& beta, const arma::vec& y, Rcpp::List& G, const arma::mat& X, const arma::vec d, const arma::mat& igroup, const arma::vec& nvec, const arma::vec& stau, const arma::uvec& nIs, const int& ngroup, const int& n, const int& ntau, const int& type, const int& Kx, const double& tol, const int& maxit);
RcppExport SEXP _QtNet_optins_struc(SEXP betaSEXP, SEXP ySEXP, SEXP GSEXP, SEXP XSEXP, SEXP dSEXP, SEXP igroupSEXP, SEXP nvecSEXP, SEXP stauSEXP, SEXP nIsSEXP, SEXP ngroupSEXP, SEXP nSEXP, SEXP ntauSEXP, SEXP typeSEXP, SEXP KxSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type stau(stauSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type nIs(nIsSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type ntau(ntauSEXP);
    Rcpp::traits::input_parameter< const int& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(optins_struc(beta, y, G, X, d, igroup, nvec, stau, nIs, ngroup, n, ntau, type, Kx, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// fcheckrank
arma::uvec fcheckrank(const arma::mat& X);
RcppExport SEXP _QtNet_fcheckrank(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fcheckrank(X));
    return rcpp_result_gen;
END_RCPP
}
// demean
arma::mat demean(arma::mat X, const arma::mat& igroup, const int& ngroup);
RcppExport SEXP _QtNet_demean(SEXP XSEXP, SEXP igroupSEXP, SEXP ngroupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    rcpp_result_gen = Rcpp::wrap(demean(X, igroup, ngroup));
    return rcpp_result_gen;
END_RCPP
}
// demean_separate
arma::mat demean_separate(arma::mat X, const arma::mat& igroup, const arma::uvec& Is, const int& ngroup, const int& n);
RcppExport SEXP _QtNet_demean_separate(SEXP XSEXP, SEXP igroupSEXP, SEXP IsSEXP, SEXP ngroupSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type Is(IsSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(demean_separate(X, igroup, Is, ngroup, n));
    return rcpp_result_gen;
END_RCPP
}
// fgmm_red
Rcpp::List fgmm_red(const arma::vec& y, const arma::mat& V, const arma::mat& ins, arma::mat& W, const arma::mat& igroup, const int& ngroup, const int& Kx, const int& Kins, const int& ntau, const int& n, const int& HAC, const bool& iv);
RcppExport SEXP _QtNet_fgmm_red(SEXP ySEXP, SEXP VSEXP, SEXP insSEXP, SEXP WSEXP, SEXP igroupSEXP, SEXP ngroupSEXP, SEXP KxSEXP, SEXP KinsSEXP, SEXP ntauSEXP, SEXP nSEXP, SEXP HACSEXP, SEXP ivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ins(insSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kins(KinsSEXP);
    Rcpp::traits::input_parameter< const int& >::type ntau(ntauSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const bool& >::type iv(ivSEXP);
    rcpp_result_gen = Rcpp::wrap(fgmm_red(y, V, ins, W, igroup, ngroup, Kx, Kins, ntau, n, HAC, iv));
    return rcpp_result_gen;
END_RCPP
}
// fgmm_struc
Rcpp::List fgmm_struc(const arma::vec& y, const arma::mat& X, const arma::mat& qy, const arma::mat& ins, arma::mat& W1, arma::mat& W2, const arma::mat& igroup, const arma::uvec& nIs, const arma::uvec& Is, const int& ngroup, const int& Kins, const int& Kx, const int& ntau, const int& n, const int& HAC, const bool& iv);
RcppExport SEXP _QtNet_fgmm_struc(SEXP ySEXP, SEXP XSEXP, SEXP qySEXP, SEXP insSEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP igroupSEXP, SEXP nIsSEXP, SEXP IsSEXP, SEXP ngroupSEXP, SEXP KinsSEXP, SEXP KxSEXP, SEXP ntauSEXP, SEXP nSEXP, SEXP HACSEXP, SEXP ivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type qy(qySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ins(insSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type igroup(igroupSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type nIs(nIsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type Is(IsSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kins(KinsSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const int& >::type ntau(ntauSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const bool& >::type iv(ivSEXP);
    rcpp_result_gen = Rcpp::wrap(fgmm_struc(y, X, qy, ins, W1, W2, igroup, nIs, Is, ngroup, Kins, Kx, ntau, n, HAC, iv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_QtNet_fQtauy", (DL_FUNC) &_QtNet_fQtauy, 10},
    {"_QtNet_fQtauyWithIndex", (DL_FUNC) &_QtNet_fQtauyWithIndex, 10},
    {"_QtNet_fQtauyIndex", (DL_FUNC) &_QtNet_fQtauyIndex, 10},
    {"_QtNet_fIndexMat", (DL_FUNC) &_QtNet_fIndexMat, 5},
    {"_QtNet_fProdWVI", (DL_FUNC) &_QtNet_fProdWVI, 3},
    {"_QtNet_fNashE", (DL_FUNC) &_QtNet_fNashE, 14},
    {"_QtNet_optins_red", (DL_FUNC) &_QtNet_optins_red, 15},
    {"_QtNet_optins_struc", (DL_FUNC) &_QtNet_optins_struc, 16},
    {"_QtNet_fcheckrank", (DL_FUNC) &_QtNet_fcheckrank, 1},
    {"_QtNet_demean", (DL_FUNC) &_QtNet_demean, 3},
    {"_QtNet_demean_separate", (DL_FUNC) &_QtNet_demean_separate, 5},
    {"_QtNet_fgmm_red", (DL_FUNC) &_QtNet_fgmm_red, 12},
    {"_QtNet_fgmm_struc", (DL_FUNC) &_QtNet_fgmm_struc, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_QtNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
