# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fCESdata <- function(X, y, z, G, friendindex, igroup, frzeroy, frzeroz, lIs, lnIs, nvec, yFMiMa, zFMiMa, n, Kx, ngroup, rho, FEnum, deriv) {
    .Call(`_QuantilePeer_fCESdata`, X, y, z, G, friendindex, igroup, frzeroy, frzeroz, lIs, lnIs, nvec, yFMiMa, zFMiMa, n, Kx, ngroup, rho, FEnum, deriv)
}

fOLS <- function(data, idX1, Is, Kx) {
    .Call(`_QuantilePeer_fOLS`, data, idX1, Is, Kx)
}

fCESgmmparms <- function(rho, beta1, idX1, idX2, X, y, z, G, friendindex, igroup, frzeroy, frzeroz, lIs, lnIs, nIs, Is, sel, W, nvec, yFMiMa, zFMiMa, n, nniso, niso, nst, Kx, Kx2, ngroup, FEnum, Kest1, Kest2, Kest, structural, HAC = 0L, COV = TRUE) {
    .Call(`_QuantilePeer_fCESgmmparms`, rho, beta1, idX1, idX2, X, y, z, G, friendindex, igroup, frzeroy, frzeroz, lIs, lnIs, nIs, Is, sel, W, nvec, yFMiMa, zFMiMa, n, nniso, niso, nst, Kx, Kx2, ngroup, FEnum, Kest1, Kest2, Kest, structural, HAC, COV)
}

fCESgmmobj <- function(rho, beta1, idX1, idX2, X, y, z, G, friendindex, igroup, frzeroy, frzeroz, lIs, lnIs, nIs, sel, W, nvec, yFMiMa, zFMiMa, n, nniso, nst, Kx, Kx2, ngroup, FEnum, structural) {
    .Call(`_QuantilePeer_fCESgmmobj`, rho, beta1, idX1, idX2, X, y, z, G, friendindex, igroup, frzeroy, frzeroz, lIs, lnIs, nIs, sel, W, nvec, yFMiMa, zFMiMa, n, nniso, nst, Kx, Kx2, ngroup, FEnum, structural)
}

fCESWeight <- function(theta, data, sel, nIs, idX1, idX2, structural, Kx, Kx2, nniso, nst) {
    .Call(`_QuantilePeer_fCESWeight`, theta, data, sel, nIs, idX1, idX2, structural, Kx, Kx2, nniso, nst)
}

fCESgmmrhoparms <- function(rho, beta1, data, sel, nIs, Is, idX1, idX2, igroup, ngroup, Kx, Kx2, nniso, niso, n, nst, Kest1, Kest2, Kest, structural, rhoinf = 0L, HAC = 0L, COV = TRUE) {
    .Call(`_QuantilePeer_fCESgmmrhoparms`, rho, beta1, data, sel, nIs, Is, idX1, idX2, igroup, ngroup, Kx, Kx2, nniso, niso, n, nst, Kest1, Kest2, Kest, structural, rhoinf, HAC, COV)
}

fCESgmmrhoobj <- function(theta, data, sel, nIs, idX1, idX2, Kx, Kx2, nniso, nst, structural, rhoinf = 0L) {
    .Call(`_QuantilePeer_fCESgmmrhoobj`, theta, data, sel, nIs, idX1, idX2, Kx, Kx2, nniso, nst, structural, rhoinf)
}

fCESParam <- function(param, covp, idX1, idX2, Kx, Kx2, estimrho, structural, COV = TRUE) {
    .Call(`_QuantilePeer_fCESParam`, param, covp, idX1, idX2, Kx, Kx2, estimrho, structural, COV)
}

fNashECES <- function(y, G, talpha, lambda, rho, friendindex, igroup, frzeroy, nvec, yFMiMa, ngroup, n, tol = 1e-10, maxit = 500L) {
    .Call(`_QuantilePeer_fNashECES`, y, G, talpha, lambda, rho, friendindex, igroup, frzeroy, nvec, yFMiMa, ngroup, n, tol, maxit)
}

fnthreads <- function(nthreads) {
    .Call(`_QuantilePeer_fnthreads`, nthreads)
}

fQtauy <- function(y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads) {
    .Call(`_QuantilePeer_fQtauy`, y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads)
}

fQtauy_EIGEN <- function(y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads) {
    .Call(`_QuantilePeer_fQtauy_EIGEN`, y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads)
}

fQtauyWithIndex <- function(y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads) {
    .Call(`_QuantilePeer_fQtauyWithIndex`, y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads)
}

fQtauyWithIndex_EIGEN <- function(y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads) {
    .Call(`_QuantilePeer_fQtauyWithIndex_EIGEN`, y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads)
}

fQtauyIndex <- function(y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads) {
    .Call(`_QuantilePeer_fQtauyIndex`, y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads)
}

fQtauyIndex_EIGEN <- function(y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads) {
    .Call(`_QuantilePeer_fQtauyIndex_EIGEN`, y, G, d, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, nthreads)
}

fIndexMat_ARMA <- function(pi1, pi2, w1, w2, n) {
    .Call(`_QuantilePeer_fIndexMat_ARMA`, pi1, pi2, w1, w2, n)
}

fIndexMat <- function(pi1, pi2, w1, w2, n) {
    .Call(`_QuantilePeer_fIndexMat`, pi1, pi2, w1, w2, n)
}

fProdWVI <- function(W, V, distance = 1L) {
    .Call(`_QuantilePeer_fProdWVI`, W, V, distance)
}

fProdWVI_EIGEN <- function(W, V, distance = 1L) {
    .Call(`_QuantilePeer_fProdWVI_EIGEN`, W, V, distance)
}

fNashE <- function(y, G, d, talpha, lambdatau, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type = 7L, tol = 1e-10, maxit = 500L, nthreads = 1L) {
    .Call(`_QuantilePeer_fNashE`, y, G, d, talpha, lambdatau, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, tol, maxit, nthreads)
}

fNashE_EIGEN <- function(y0, G, d, talpha, lambdatau, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type = 7L, tol = 1e-10, maxit = 500L, nthreads = 1L) {
    .Call(`_QuantilePeer_fNashE_EIGEN`, y0, G, d, talpha, lambdatau, igroup, group, groupidx, nvec, stau, ngroup, n, ntau, type, tol, maxit, nthreads)
}

simInstrqpeer <- function(y, qy, X, G, d, igroup, group, groupidx, estimate, nIs, nvec, stau, stauInst, boot, fixedeffects, structural, nthreads, seed, type = 7L, tol = 1e-10, maxit = 500L) {
    .Call(`_QuantilePeer_simInstrqpeer`, y, qy, X, G, d, igroup, group, groupidx, estimate, nIs, nvec, stau, stauInst, boot, fixedeffects, structural, nthreads, seed, type, tol, maxit)
}

simInstrqpeer_EIGEN <- function(y, qy, X, G, d, igroup, group, groupidx, estimate, nIs, nvec, stau, boot, structural, fixedeffects, nthreads, seed, type = 7L, tol = 1e-10, maxit = 500L) {
    .Call(`_QuantilePeer_simInstrqpeer_EIGEN`, y, qy, X, G, d, igroup, group, groupidx, estimate, nIs, nvec, stau, boot, structural, fixedeffects, nthreads, seed, type, tol, maxit)
}

fylim_ARMA <- function(y, Gy, G, talpha, igroup, ngroup, lambda, nthreads) {
    invisible(.Call(`_QuantilePeer_fylim_ARMA`, y, Gy, G, talpha, igroup, ngroup, lambda, nthreads))
}

fylim <- function(G, talpha, igroup, nvec, ngroup, lambda, n, nthreads) {
    .Call(`_QuantilePeer_fylim`, G, talpha, igroup, nvec, ngroup, lambda, n, nthreads)
}

fJIVE_redInd <- function(y, V, ins, Kx, Kins, ntau, n, Kest, HAC = 0L, COV = TRUE) {
    .Call(`_QuantilePeer_fJIVE_redInd`, y, V, ins, Kx, Kins, ntau, n, Kest, HAC, COV)
}

fJIVE2_redInd <- function(y, V, ins, Kx, Kins, ntau, n, Kest, HAC = 0L, COV = TRUE) {
    .Call(`_QuantilePeer_fJIVE2_redInd`, y, V, ins, Kx, Kins, ntau, n, Kest, HAC, COV)
}

fJIVE_redClu <- function(y, V, ins, igroup, nvec, ngroup, Kx, Kins, ntau, n, Kest, COV) {
    .Call(`_QuantilePeer_fJIVE_redClu`, y, V, ins, igroup, nvec, ngroup, Kx, Kins, ntau, n, Kest, COV)
}

fJIVE2_redClu <- function(y, V, ins, igroup, nvec, ngroup, Kx, Kins, ntau, n, Kest, COV) {
    .Call(`_QuantilePeer_fJIVE2_redClu`, y, V, ins, igroup, nvec, ngroup, Kx, Kins, ntau, n, Kest, COV)
}

fJIVE_strucInd <- function(y, X, qy, ins, idX1, idX2, nIs, Is, Kx1, Kx2, Kins, ntau, n, Kest1, HAC = 0L, COV = TRUE) {
    .Call(`_QuantilePeer_fJIVE_strucInd`, y, X, qy, ins, idX1, idX2, nIs, Is, Kx1, Kx2, Kins, ntau, n, Kest1, HAC, COV)
}

fJIVE2_strucInd <- function(y, X, qy, ins, idX1, idX2, nIs, Is, Kx1, Kx2, Kins, ntau, n, Kest1, HAC = 0L, COV = TRUE) {
    .Call(`_QuantilePeer_fJIVE2_strucInd`, y, X, qy, ins, idX1, idX2, nIs, Is, Kx1, Kx2, Kins, ntau, n, Kest1, HAC, COV)
}

fJIVE_strucClu <- function(y, X, qy, ins, idX1, idX2, nIs, Is, LnIs, LIs, igroup, nvecnIs, hasnIs, hasIs, ngroup, Kx1, Kx2, Kins, ntau, n, COV = TRUE) {
    .Call(`_QuantilePeer_fJIVE_strucClu`, y, X, qy, ins, idX1, idX2, nIs, Is, LnIs, LIs, igroup, nvecnIs, hasnIs, hasIs, ngroup, Kx1, Kx2, Kins, ntau, n, COV)
}

fJIVE2_strucClu <- function(y, X, qy, ins, idX1, idX2, nIs, Is, LnIs, LIs, igroup, hasnIs, hasIs, ngroup, Kx1, Kx2, Kins, ntau, n, COV = TRUE) {
    .Call(`_QuantilePeer_fJIVE2_strucClu`, y, X, qy, ins, idX1, idX2, nIs, Is, LnIs, LIs, igroup, hasnIs, hasIs, ngroup, Kx1, Kx2, Kins, ntau, n, COV)
}

fcheckrankEigen <- function(X, tol = 1e-10) {
    .Call(`_QuantilePeer_fcheckrankEigen`, X, tol)
}

Demean <- function(X, igroup, ngroup) {
    .Call(`_QuantilePeer_Demean`, X, igroup, ngroup)
}

Demean_separate <- function(X, igroup, LIs, LnIs, ngroup, n) {
    .Call(`_QuantilePeer_Demean_separate`, X, igroup, LIs, LnIs, ngroup, n)
}

fdatadiagnostic <- function(y, endo, X, ins, theta, idX1, idX2, igroup, nIs, LIs, LnIs, n, ngroup, ntau, struc, FE) {
    .Call(`_QuantilePeer_fdatadiagnostic`, y, endo, X, ins, theta, idX1, idX2, igroup, nIs, LIs, LnIs, n, ngroup, ntau, struc, FE)
}

fassignfold <- function(nvec, nfold) {
    .Call(`_QuantilePeer_fassignfold`, nvec, nfold)
}

fpredinst <- function(endo, ins, fold, nthreads) {
    .Call(`_QuantilePeer_fpredinst`, endo, ins, fold, nthreads)
}

fgmm_red <- function(y, V, ins, W, igroup, ngroup, Kx, Kins, ntau, n, Kest, HAC = 0L, iv = TRUE) {
    .Call(`_QuantilePeer_fgmm_red`, y, V, ins, W, igroup, ngroup, Kx, Kins, ntau, n, Kest, HAC, iv)
}

fgmm_struc <- function(y, X, qy, ins, W1, W2, idX1, idX2, Kx1, Kx2, igroup, nIs, Is, ngroup, ngroup2, Kins, Kx, ntau, n, Kest1, Kest2, HAC = 0L, iv = TRUE) {
    .Call(`_QuantilePeer_fgmm_struc`, y, X, qy, ins, W1, W2, idX1, idX2, Kx1, Kx2, igroup, nIs, Is, ngroup, ngroup2, Kins, Kx, ntau, n, Kest1, Kest2, HAC, iv)
}

fStructParam <- function(param, covp, idX1, idX2, ntau, Kx, Kx1, Kx2, COV = TRUE) {
    .Call(`_QuantilePeer_fStructParam`, param, covp, idX1, idX2, ntau, Kx, Kx1, Kx2, COV)
}

fFstat <- function(y, X, index, igroup, ngroup, HAC = 0L) {
    .Call(`_QuantilePeer_fFstat`, y, X, index, igroup, ngroup, HAC)
}

fKPstat <- function(qy, Z, index, igroup, HAC = 0L) {
    .Call(`_QuantilePeer_fKPstat`, qy, Z, index, igroup, HAC)
}

fStructParamFull <- function(param, covp, ntau, Kx1, Kx2, quantile, ces = FALSE) {
    .Call(`_QuantilePeer_fStructParamFull`, param, covp, ntau, Kx1, Kx2, quantile, ces)
}

fParamFull <- function(param, covp, ntau, Kx1, Kx2) {
    .Call(`_QuantilePeer_fParamFull`, param, covp, ntau, Kx1, Kx2)
}

fgmm_red_boot <- function(y, V, ins, W, igroup, LnIs, LIs, ngroup, Kx, Kins, ntau, Kest, iv, boot, nthreads, seed, print, overident) {
    .Call(`_QuantilePeer_fgmm_red_boot`, y, V, ins, W, igroup, LnIs, LIs, ngroup, Kx, Kins, ntau, Kest, iv, boot, nthreads, seed, print, overident)
}

fKPstat_boot <- function(qy, Z, index, igroup, LnIs, LIs, ngroup, boot, nthreads, seed, print) {
    .Call(`_QuantilePeer_fKPstat_boot`, qy, Z, index, igroup, LnIs, LIs, ngroup, boot, nthreads, seed, print)
}

Cov2ThetaRed <- function(Z1, W1, e1, theta1, Z2, W2, e2, theta2, X, qy, Kest, ngroup, cumsn, HAC = 0L, full = FALSE) {
    .Call(`_QuantilePeer_Cov2ThetaRed`, Z1, W1, e1, theta1, Z2, W2, e2, theta2, X, qy, Kest, ngroup, cumsn, HAC, full)
}

Cov2ThetaStruc <- function(Z1, W21, e1, theta1, Z2, W22, e2, theta2, X, qy, W1, Kest1, Kest2, idX1, idX2, nIs, Is, ngroup, cumsn, HAC = 0L, full = FALSE) {
    .Call(`_QuantilePeer_Cov2ThetaStruc`, Z1, W21, e1, theta1, Z2, W22, e2, theta2, X, qy, W1, Kest1, Kest2, idX1, idX2, nIs, Is, ngroup, cumsn, HAC, full)
}

validZ2SarganRed <- function(Z1, W1, e1, theta1, Z2, W2, e2, theta2, X, qy, Kest, ngroup, cumsn, HAC = 0L, full = FALSE) {
    .Call(`_QuantilePeer_validZ2SarganRed`, Z1, W1, e1, theta1, Z2, W2, e2, theta2, X, qy, Kest, ngroup, cumsn, HAC, full)
}

validZ2SarganStruc <- function(Z1, W21, e1, theta1, Z2, W22, e2, theta2, X, qy, W1, Kest1, Kest2, idX1, idX2, nIs, Is, ngroup, cumsn, HAC = 0L, full = FALSE) {
    .Call(`_QuantilePeer_validZ2SarganStruc`, Z1, W21, e1, theta1, Z2, W22, e2, theta2, X, qy, W1, Kest1, Kest2, idX1, idX2, nIs, Is, ngroup, cumsn, HAC, full)
}

fTestMonotone <- function(thetahat, Sigma, a, thetasimu, Boot, maxit, eps_f, eps_g) {
    .Call(`_QuantilePeer_fTestMonotone`, thetahat, Sigma, a, thetasimu, Boot, maxit, eps_f, eps_g)
}

fEncompassingStruc <- function(y, qy1, Z1, Kest11, Kest21, qy2, Z2, Kest12, Kest22, X, idX1, idX2, LnIs, LIs, ngroup, iv1, iv2, boot, nthreads, seed, print, full) {
    .Call(`_QuantilePeer_fEncompassingStruc`, y, qy1, Z1, Kest11, Kest21, qy2, Z2, Kest12, Kest22, X, idX1, idX2, LnIs, LIs, ngroup, iv1, iv2, boot, nthreads, seed, print, full)
}

fEncompassingRed <- function(y, qy1, Z1, Kest1, qy2, Z2, Kest2, X, igroup, LnIs, LIs, ngroup, iv1, iv2, boot, nthreads, seed, print, full) {
    .Call(`_QuantilePeer_fEncompassingRed`, y, qy1, Z1, Kest1, qy2, Z2, Kest2, X, igroup, LnIs, LIs, ngroup, iv1, iv2, boot, nthreads, seed, print, full)
}

