# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fgPIyP <- function(y, G, d, igroup, nvec, ngroup, n) {
    .Call(`_QtNet_fgPIyP`, y, G, d, igroup, nvec, ngroup, n)
}

fQtauy <- function(y, G, d, igroup, nvec, stau, ngroup, n, ntau, type) {
    .Call(`_QtNet_fQtauy`, y, G, d, igroup, nvec, stau, ngroup, n, ntau, type)
}

fQtauyWithIndex <- function(y, G, d, igroup, nvec, stau, ngroup, n, ntau, type) {
    .Call(`_QtNet_fQtauyWithIndex`, y, G, d, igroup, nvec, stau, ngroup, n, ntau, type)
}

fQtauyIndex <- function(y, G, d, igroup, nvec, stau, ngroup, n, ntau, type) {
    .Call(`_QtNet_fQtauyIndex`, y, G, d, igroup, nvec, stau, ngroup, n, ntau, type)
}

fIndexMat <- function(pi1, pi2, w1, w2, n) {
    .Call(`_QtNet_fIndexMat`, pi1, pi2, w1, w2, n)
}

fProdWVI <- function(W, V, distance = 1L) {
    .Call(`_QtNet_fProdWVI`, W, V, distance)
}

fNashE <- function(y, G, d, talpha, lambdatau, igroup, nvec, stau, ngroup, n, ntau, type = 7L, tol = 1e-10, maxit = 500L) {
    .Call(`_QtNet_fNashE`, y, G, d, talpha, lambdatau, igroup, nvec, stau, ngroup, n, ntau, type, tol, maxit)
}

optins_red <- function(beta, y, G, X, d, igroup, nvec, stau, ngroup, n, ntau, type, Kx, tol, maxit) {
    .Call(`_QtNet_optins_red`, beta, y, G, X, d, igroup, nvec, stau, ngroup, n, ntau, type, Kx, tol, maxit)
}

optins_struc <- function(beta, y, G, X, d, igroup, nvec, stau, nIs, ngroup, n, ntau, type, Kx, tol, maxit) {
    .Call(`_QtNet_optins_struc`, beta, y, G, X, d, igroup, nvec, stau, nIs, ngroup, n, ntau, type, Kx, tol, maxit)
}

fJIVE_redInd <- function(y, V, ins, Kx, Kins, ntau, n, Kest, HAC = 0L, COV = TRUE) {
    .Call(`_QtNet_fJIVE_redInd`, y, V, ins, Kx, Kins, ntau, n, Kest, HAC, COV)
}

fJIVE2_redInd <- function(y, V, ins, Kx, Kins, ntau, n, Kest, HAC = 0L, COV = TRUE) {
    .Call(`_QtNet_fJIVE2_redInd`, y, V, ins, Kx, Kins, ntau, n, Kest, HAC, COV)
}

fJIVE_redClu <- function(y, V, ins, igroup, nvec, ngroup, Kx, Kins, ntau, n, Kest, COV) {
    .Call(`_QtNet_fJIVE_redClu`, y, V, ins, igroup, nvec, ngroup, Kx, Kins, ntau, n, Kest, COV)
}

fJIVE2_redClu <- function(y, V, ins, igroup, nvec, ngroup, Kx, Kins, ntau, n, Kest, COV) {
    .Call(`_QtNet_fJIVE2_redClu`, y, V, ins, igroup, nvec, ngroup, Kx, Kins, ntau, n, Kest, COV)
}

fJIVE_strucInd <- function(y, X, qy, ins, idX1, idX2, nIs, Is, Kx1, Kx2, Kins, ntau, n, Kest, HAC = 0L, COV = TRUE) {
    .Call(`_QtNet_fJIVE_strucInd`, y, X, qy, ins, idX1, idX2, nIs, Is, Kx1, Kx2, Kins, ntau, n, Kest, HAC, COV)
}

fJIVE2_strucInd <- function(y, X, qy, ins, idX1, idX2, nIs, Is, Kx1, Kx2, Kins, ntau, n, Kest, HAC = 0L, COV = TRUE) {
    .Call(`_QtNet_fJIVE2_strucInd`, y, X, qy, ins, idX1, idX2, nIs, Is, Kx1, Kx2, Kins, ntau, n, Kest, HAC, COV)
}

fJIVE_strucClu <- function(y, X, qy, ins, idX1, idX2, nIs, Is, LnIs, LIs, igroup, nvecnIs, hasnIs, hasIs, ngroup, Kx1, Kx2, Kins, ntau, n, Kest, COV = TRUE) {
    .Call(`_QtNet_fJIVE_strucClu`, y, X, qy, ins, idX1, idX2, nIs, Is, LnIs, LIs, igroup, nvecnIs, hasnIs, hasIs, ngroup, Kx1, Kx2, Kins, ntau, n, Kest, COV)
}

fJIVE2_strucClu <- function(y, X, qy, ins, idX1, idX2, nIs, Is, LnIs, LIs, igroup, hasnIs, hasIs, ngroup, Kx1, Kx2, Kins, ntau, n, Kest, COV = TRUE) {
    .Call(`_QtNet_fJIVE2_strucClu`, y, X, qy, ins, idX1, idX2, nIs, Is, LnIs, LIs, igroup, hasnIs, hasIs, ngroup, Kx1, Kx2, Kins, ntau, n, Kest, COV)
}

fcheckrankEigen <- function(X, tol = 1e-10) {
    .Call(`_QtNet_fcheckrankEigen`, X, tol)
}

demean <- function(X, igroup, ngroup) {
    .Call(`_QtNet_demean`, X, igroup, ngroup)
}

demean_separate <- function(X, igroup, LIs, LnIs, ngroup, n) {
    .Call(`_QtNet_demean_separate`, X, igroup, LIs, LnIs, ngroup, n)
}

fdatadiagnostic <- function(y, endo, X, ins, theta, idX1, idX2, igroup, nIs, LIs, LnIs, n, ngroup, ntau, struc, FE) {
    .Call(`_QtNet_fdatadiagnostic`, y, endo, X, ins, theta, idX1, idX2, igroup, nIs, LIs, LnIs, n, ngroup, ntau, struc, FE)
}

fgmm_red <- function(y, V, ins, W, igroup, ngroup, Kx, Kins, ntau, n, Kest, HAC = 0L, iv = TRUE) {
    .Call(`_QtNet_fgmm_red`, y, V, ins, W, igroup, ngroup, Kx, Kins, ntau, n, Kest, HAC, iv)
}

fgmm_redARMA <- function(y, V, ins, W, igroup, ngroup, Kx, Kins, ntau, n, Kest, HAC = 0L, iv = TRUE) {
    .Call(`_QtNet_fgmm_redARMA`, y, V, ins, W, igroup, ngroup, Kx, Kins, ntau, n, Kest, HAC, iv)
}

fgmm_struc <- function(y, X, qy, ins, W1, W2, idX1, idX2, Kx1, Kx2, igroup, nIs, Is, ngroup, Kins, Kx, ntau, n, Kest, HAC = 0L, iv = TRUE) {
    .Call(`_QtNet_fgmm_struc`, y, X, qy, ins, W1, W2, idX1, idX2, Kx1, Kx2, igroup, nIs, Is, ngroup, Kins, Kx, ntau, n, Kest, HAC, iv)
}

fgmm_strucARMA <- function(y, X, qy, ins, W1, W2, idX1, idX2, Kx1, Kx2, igroup, nIs, Is, ngroup, Kins, Kx, ntau, n, Kest, HAC = 0L, iv = TRUE) {
    .Call(`_QtNet_fgmm_strucARMA`, y, X, qy, ins, W1, W2, idX1, idX2, Kx1, Kx2, igroup, nIs, Is, ngroup, Kins, Kx, ntau, n, Kest, HAC, iv)
}

fStructParam <- function(param, covp, idX1, idX2, ntau, Kx, Kx1, Kx2, COV = TRUE) {
    .Call(`_QtNet_fStructParam`, param, covp, idX1, idX2, ntau, Kx, Kx1, Kx2, COV)
}

fFstathomo <- function(y, Xc, Xu) {
    .Call(`_QtNet_fFstathomo`, y, Xc, Xu)
}

fFstathomoARMA <- function(y, Xc, Xu) {
    .Call(`_QtNet_fFstathomoARMA`, y, Xc, Xu)
}

fFstat <- function(y, X, index, igroup, ngroup, HAC = 0L) {
    .Call(`_QtNet_fFstat`, y, X, index, igroup, ngroup, HAC)
}

fFstatARMA <- function(y, X, index, igroup, ngroup, HAC = 0L) {
    .Call(`_QtNet_fFstatARMA`, y, X, index, igroup, ngroup, HAC)
}

