# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fgPIyP <- function(y, G, d, igroup, nvec, ngroup, n) {
    .Call(`_QtNet_fgPIyP`, y, G, d, igroup, nvec, ngroup, n)
}

fQWeightIndex <- function(w2, pi1, pi2, lgP, lcumsumgP, lIyP, d, stau, sm, n, ntau) {
    invisible(.Call(`_QtNet_fQWeightIndex`, w2, pi1, pi2, lgP, lcumsumgP, lIyP, d, stau, sm, n, ntau))
}

fQtauyVars <- function(y, Vars, G, d, igroup, nvec, stau, sm, ngroup, colVars, n, ntau) {
    .Call(`_QtNet_fQtauyVars`, y, Vars, G, d, igroup, nvec, stau, sm, ngroup, colVars, n, ntau)
}

fQtauy <- function(y, G, d, igroup, nvec, stau, sm, ngroup, n, ntau) {
    .Call(`_QtNet_fQtauy`, y, G, d, igroup, nvec, stau, sm, ngroup, n, ntau)
}

BR <- function(talpha, Qtauy, lambdatau) {
    .Call(`_QtNet_BR`, talpha, Qtauy, lambdatau)
}

fNashE <- function(y, G, d, talpha, lambdatau, igroup, nvec, stau, sm, ngroup, n, ntau, tol = 1e-10, maxit = 500L) {
    .Call(`_QtNet_fNashE`, y, G, d, talpha, lambdatau, igroup, nvec, stau, sm, ngroup, n, ntau, tol, maxit)
}

